/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Proyecto;

import java.awt.Color;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author matri
 */
public class frmAlumnos extends javax.swing.JFrame {
    
    String status = "Activo"; 

    Conexion conexion = new Conexion();
    /**
     * Creates new form frmAlumnos
     */
    public frmAlumnos() {
        initComponents();
        limpiarAlta();
        limpiarModificar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dialogoAltasAlumnos = new javax.swing.JDialog();
        jPanel1 = new javax.swing.JPanel();
        txtNombre = new javax.swing.JTextField();
        txtApellidoPaterno = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtApellidoMaterno = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        spnEdad = new javax.swing.JSpinner();
        cmbSalon = new javax.swing.JComboBox<>();
        cmbStatus = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        lbID = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btnRegresar = new javax.swing.JButton();
        btnAgregar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        dialogoConsultaAlumnos = new javax.swing.JDialog();
        jPanel3 = new javax.swing.JPanel();
        txtcNombre = new javax.swing.JTextField();
        txtcApellidoPaterno = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtcApellidoMaterno = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        spncEdad = new javax.swing.JSpinner();
        cmbcSalon = new javax.swing.JComboBox<>();
        cmbcStatus = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        lbcID = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        btncRegresar = new javax.swing.JButton();
        btncLimpiar = new javax.swing.JButton();
        txtBusqueda = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        btncActualizar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        dgvInformacionAlumno = new javax.swing.JTable();
        rdbActivo = new javax.swing.JRadioButton();
        rdbInactivo = new javax.swing.JRadioButton();
        dialogoAltasUsuarios = new javax.swing.JDialog();
        dialogoConsultaUsuarios = new javax.swing.JDialog();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuAlumnos = new javax.swing.JMenu();
        menuItemAltasAlumnos = new javax.swing.JMenuItem();
        menuItemConsulta = new javax.swing.JMenuItem();
        menuUsuarios = new javax.swing.JMenu();
        menuItemAltaUsuarios = new javax.swing.JMenuItem();
        menuItemConsultaUsuarios = new javax.swing.JMenuItem();

        dialogoAltasAlumnos.setTitle("Alta de alumnos");

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        txtNombre.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        txtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreKeyTyped(evt);
            }
        });

        txtApellidoPaterno.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        txtApellidoPaterno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtApellidoPaternoKeyTyped(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        jLabel1.setText("Nombre(s)");

        jLabel2.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        jLabel2.setText("Apellido Paterno");

        jLabel3.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        jLabel3.setText("Apellido Materno");

        txtApellidoMaterno.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        txtApellidoMaterno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtApellidoMaternoKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txtApellidoPaterno, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
                    .addComponent(txtNombre)
                    .addComponent(txtApellidoMaterno))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtApellidoPaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtApellidoMaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26))
        );

        jPanel2.setBackground(new java.awt.Color(255, 204, 204));

        jLabel4.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        jLabel4.setText("Edad");

        jLabel5.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        jLabel5.setText("Salón");

        jLabel6.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        jLabel6.setText("Status");

        spnEdad.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        spnEdad.setModel(new javax.swing.SpinnerNumberModel(9, 8, 100, 1));

        cmbSalon.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        cmbSalon.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "3A", "3B", "3C", "4A", "4B", "4C" }));

        cmbStatus.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        cmbStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Activo", "Inactivo" }));
        cmbStatus.setEnabled(false);

        jLabel7.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        jLabel7.setText("Id_alumno");

        lbID.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        lbID.setText("0");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(spnEdad))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(cmbSalon, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(cmbStatus, 0, 109, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(lbID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(spnEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(lbID))
                .addGap(66, 66, 66)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cmbSalon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(cmbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel9.setFont(new java.awt.Font("Century Schoolbook", 1, 24)); // NOI18N
        jLabel9.setText("ALTA DE ALUMNOS");

        btnRegresar.setBackground(new java.awt.Color(244, 186, 186));
        btnRegresar.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        btnAgregar.setBackground(new java.awt.Color(186, 244, 185));
        btnAgregar.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        btnLimpiar.setBackground(new java.awt.Color(181, 226, 255));
        btnLimpiar.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dialogoAltasAlumnosLayout = new javax.swing.GroupLayout(dialogoAltasAlumnos.getContentPane());
        dialogoAltasAlumnos.getContentPane().setLayout(dialogoAltasAlumnosLayout);
        dialogoAltasAlumnosLayout.setHorizontalGroup(
            dialogoAltasAlumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dialogoAltasAlumnosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addGap(251, 251, 251))
            .addGroup(dialogoAltasAlumnosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dialogoAltasAlumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dialogoAltasAlumnosLayout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(dialogoAltasAlumnosLayout.createSequentialGroup()
                        .addComponent(btnRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        dialogoAltasAlumnosLayout.setVerticalGroup(
            dialogoAltasAlumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogoAltasAlumnosLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addGroup(dialogoAltasAlumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addGroup(dialogoAltasAlumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        dialogoConsultaAlumnos.setTitle("Consulta de alumnos");

        jPanel3.setBackground(new java.awt.Color(204, 204, 255));

        txtcNombre.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        txtcNombre.setEnabled(false);
        txtcNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtcNombreKeyTyped(evt);
            }
        });

        txtcApellidoPaterno.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        txtcApellidoPaterno.setEnabled(false);
        txtcApellidoPaterno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtcApellidoPaternoKeyTyped(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        jLabel10.setText("Nombre(s)");

        jLabel11.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        jLabel11.setText("Apellido Paterno");

        jLabel12.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        jLabel12.setText("Apellido Materno");

        txtcApellidoMaterno.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        txtcApellidoMaterno.setEnabled(false);
        txtcApellidoMaterno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtcApellidoMaternoKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txtcApellidoPaterno, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
                    .addComponent(txtcNombre)
                    .addComponent(txtcApellidoMaterno))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtcNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(43, 43, 43)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtcApellidoPaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtcApellidoMaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26))
        );

        jPanel4.setBackground(new java.awt.Color(255, 204, 204));

        jLabel13.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        jLabel13.setText("Edad");

        jLabel14.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        jLabel14.setText("Salón");

        jLabel15.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        jLabel15.setText("Status");

        spncEdad.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        spncEdad.setModel(new javax.swing.SpinnerNumberModel(9, 8, 100, 1));
        spncEdad.setEnabled(false);

        cmbcSalon.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        cmbcSalon.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "3A", "3B", "3C", "4A", "4B", "4C" }));
        cmbcSalon.setEnabled(false);

        cmbcStatus.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        cmbcStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Activo", "Inactivo" }));
        cmbcStatus.setEnabled(false);

        jLabel16.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        jLabel16.setText("Id_alumno");

        lbcID.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        lbcID.setText("numero");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGap(18, 18, 18)
                        .addComponent(spncEdad))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addGap(18, 18, 18)
                        .addComponent(cmbcSalon, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addGap(18, 18, 18)
                        .addComponent(cmbcStatus, 0, 108, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addGap(18, 18, 18)
                        .addComponent(lbcID)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(5, 5, 5))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(spncEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16)
                    .addComponent(lbcID))
                .addGap(66, 66, 66)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(cmbcSalon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(cmbcStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(56, Short.MAX_VALUE))
        );

        jLabel18.setFont(new java.awt.Font("Century Schoolbook", 1, 24)); // NOI18N
        jLabel18.setText("CONSULTA DE ALUMNOS");

        btncRegresar.setBackground(new java.awt.Color(244, 186, 186));
        btncRegresar.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        btncRegresar.setText("Regresar");
        btncRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncRegresarActionPerformed(evt);
            }
        });

        btncLimpiar.setBackground(new java.awt.Color(181, 226, 255));
        btncLimpiar.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        btncLimpiar.setText("Limpiar");
        btncLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncLimpiarActionPerformed(evt);
            }
        });

        txtBusqueda.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        txtBusqueda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtBusquedaKeyTyped(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        jLabel19.setText("Busqueda de alumnos:");

        btncActualizar.setBackground(new java.awt.Color(186, 244, 185));
        btncActualizar.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        btncActualizar.setText("Actualizar datos");
        btncActualizar.setEnabled(false);
        btncActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncActualizarActionPerformed(evt);
            }
        });

        dgvInformacionAlumno.setBackground(new java.awt.Color(255, 255, 204));
        dgvInformacionAlumno.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "nombre", "Apellido Paterno", "Apellido Materno", "Edad", "Salón", "status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        dgvInformacionAlumno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dgvInformacionAlumnoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(dgvInformacionAlumno);

        rdbActivo.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        rdbActivo.setSelected(true);
        rdbActivo.setText("Activo");
        rdbActivo.setEnabled(false);
        rdbActivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbActivoActionPerformed(evt);
            }
        });

        rdbInactivo.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        rdbInactivo.setText("Inactivo");
        rdbInactivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbInactivoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dialogoConsultaAlumnosLayout = new javax.swing.GroupLayout(dialogoConsultaAlumnos.getContentPane());
        dialogoConsultaAlumnos.getContentPane().setLayout(dialogoConsultaAlumnosLayout);
        dialogoConsultaAlumnosLayout.setHorizontalGroup(
            dialogoConsultaAlumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogoConsultaAlumnosLayout.createSequentialGroup()
                .addGroup(dialogoConsultaAlumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(dialogoConsultaAlumnosLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(dialogoConsultaAlumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(dialogoConsultaAlumnosLayout.createSequentialGroup()
                            .addGap(236, 236, 236)
                            .addComponent(jLabel18))
                        .addGroup(dialogoConsultaAlumnosLayout.createSequentialGroup()
                            .addGap(20, 20, 20)
                            .addComponent(jLabel19)
                            .addGap(17, 17, 17)
                            .addComponent(txtBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(50, 50, 50)
                            .addComponent(rdbActivo)
                            .addGap(47, 47, 47)
                            .addComponent(rdbInactivo))
                        .addGroup(dialogoConsultaAlumnosLayout.createSequentialGroup()
                            .addGap(20, 20, 20)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 740, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(dialogoConsultaAlumnosLayout.createSequentialGroup()
                            .addGap(20, 20, 20)
                            .addComponent(btncRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(350, 350, 350)
                            .addComponent(btncLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(10, 10, 10)
                            .addComponent(btncActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        dialogoConsultaAlumnosLayout.setVerticalGroup(
            dialogoConsultaAlumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogoConsultaAlumnosLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel18)
                .addGap(52, 52, 52)
                .addGroup(dialogoConsultaAlumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel19)
                    .addComponent(txtBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rdbActivo)
                    .addComponent(rdbInactivo))
                .addGap(25, 25, 25)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addGroup(dialogoConsultaAlumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(dialogoConsultaAlumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btncRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btncLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btncActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(63, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout dialogoAltasUsuariosLayout = new javax.swing.GroupLayout(dialogoAltasUsuarios.getContentPane());
        dialogoAltasUsuarios.getContentPane().setLayout(dialogoAltasUsuariosLayout);
        dialogoAltasUsuariosLayout.setHorizontalGroup(
            dialogoAltasUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        dialogoAltasUsuariosLayout.setVerticalGroup(
            dialogoAltasUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout dialogoConsultaUsuariosLayout = new javax.swing.GroupLayout(dialogoConsultaUsuarios.getContentPane());
        dialogoConsultaUsuarios.getContentPane().setLayout(dialogoConsultaUsuariosLayout);
        dialogoConsultaUsuariosLayout.setHorizontalGroup(
            dialogoConsultaUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        dialogoConsultaUsuariosLayout.setVerticalGroup(
            dialogoConsultaUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        menuAlumnos.setText("Alumnos");

        menuItemAltasAlumnos.setText("Alta de alumnos");
        menuItemAltasAlumnos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemAltasAlumnosActionPerformed(evt);
            }
        });
        menuAlumnos.add(menuItemAltasAlumnos);

        menuItemConsulta.setText("Consulta de alumnos");
        menuItemConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemConsultaActionPerformed(evt);
            }
        });
        menuAlumnos.add(menuItemConsulta);

        jMenuBar1.add(menuAlumnos);

        menuUsuarios.setText("Usuarios");

        menuItemAltaUsuarios.setText("Alta de usuarios");
        menuUsuarios.add(menuItemAltaUsuarios);

        menuItemConsultaUsuarios.setText("Consulta de usuarios");
        menuUsuarios.add(menuItemConsultaUsuarios);

        jMenuBar1.add(menuUsuarios);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 775, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 450, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuItemAltasAlumnosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemAltasAlumnosActionPerformed
        dialogoAltasAlumnos.getContentPane().setBackground(Color.white);
        dialogoAltasAlumnos.setSize(775,409);
        dialogoAltasAlumnos.setVisible(true);
    }//GEN-LAST:event_menuItemAltasAlumnosActionPerformed

    private void rdbInactivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbInactivoActionPerformed
        this.status = "Inactivo";
        rdbActivo.setSelected(false);
        rdbActivo.setEnabled(true);
        rdbInactivo.setEnabled(false);
        llenarTabla();
    }//GEN-LAST:event_rdbInactivoActionPerformed

    private void menuItemConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemConsultaActionPerformed
        dialogoConsultaAlumnos.getContentPane().setBackground(Color.white);
        dialogoConsultaAlumnos.setSize(795,590);
        dialogoConsultaAlumnos.setVisible(true);
    }//GEN-LAST:event_menuItemConsultaActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        String nombres = txtNombre.getText();
        String apellidoPaterno = txtApellidoPaterno.getText();
        String apellidoMaterno = txtApellidoMaterno.getText();
        String edad = spnEdad.getValue().toString();
        String salon = cmbSalon.getItemAt(cmbSalon.getSelectedIndex());
        
        if(!nombres.equals("") && !apellidoPaterno.equals("") && !apellidoMaterno.equals("")
            && !edad.equals("") && !salon.equals("")){
            boolean registroExitoso = conexion.registrarAlumno(nombres, apellidoPaterno, apellidoMaterno, edad, salon);
        
            if (registroExitoso){
                JOptionPane.showMessageDialog(this, "El Alumno ha sido registrado satisfactorimente", "Éxito", JOptionPane.INFORMATION_MESSAGE);
                limpiarAlta();
            }else{
                JOptionPane.showMessageDialog(this, "Ha ocurrido un error\nEl Alumno no ha sido registrado", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }else{
            JOptionPane.showMessageDialog(this, "Ha ocurrido un error\nDebe de llenar todos los campos", "Error", JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void txtNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKeyTyped
        Character caracter = evt.getKeyChar();

        if(caracter.toString().matches("[^A-za-z á-ñÑ]|_") || (caracter == '\b')){
            evt.consume();
        }
    }//GEN-LAST:event_txtNombreKeyTyped

    private void txtApellidoPaternoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtApellidoPaternoKeyTyped
        Character caracter = evt.getKeyChar();

        if(caracter.toString().matches("[^A-za-z á-ñÑ]|_") || (caracter == '\b')){
            evt.consume();
        }
    }//GEN-LAST:event_txtApellidoPaternoKeyTyped

    private void txtApellidoMaternoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtApellidoMaternoKeyTyped
        Character caracter = evt.getKeyChar();

        if(caracter.toString().matches("[^A-za-z á-ñÑ]|_") || (caracter == '\b')){
            evt.consume();
        }
    }//GEN-LAST:event_txtApellidoMaternoKeyTyped

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        limpiarAlta();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        dialogoAltasAlumnos.dispose();
        limpiarAlta();
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void rdbActivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbActivoActionPerformed
        this.status = "Activo";
        rdbInactivo.setSelected(false);
        rdbInactivo.setEnabled(true);
        rdbActivo.setEnabled(false);
        llenarTabla();
    }//GEN-LAST:event_rdbActivoActionPerformed

    private void txtBusquedaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBusquedaKeyTyped
        llenarTabla();
    }//GEN-LAST:event_txtBusquedaKeyTyped

    private void dgvInformacionAlumnoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dgvInformacionAlumnoMouseClicked
        if (dgvInformacionAlumno.getSelectedRow() != -1) {
            Integer ID = (Integer) dgvInformacionAlumno.getModel().getValueAt(dgvInformacionAlumno.getSelectedRow(), 0);
            String nombre = (String) dgvInformacionAlumno.getModel().getValueAt(dgvInformacionAlumno.getSelectedRow(), 1);
            String apellido_paterno = (String) dgvInformacionAlumno.getModel().getValueAt(dgvInformacionAlumno.getSelectedRow(), 2);
            String apellido_materno = (String) dgvInformacionAlumno.getModel().getValueAt(dgvInformacionAlumno.getSelectedRow(), 3);
            int edad = (int) dgvInformacionAlumno.getModel().getValueAt(dgvInformacionAlumno.getSelectedRow(), 4);
            String salon = (String) dgvInformacionAlumno.getModel().getValueAt(dgvInformacionAlumno.getSelectedRow(), 5);
            String status = (String) dgvInformacionAlumno.getModel().getValueAt(dgvInformacionAlumno.getSelectedRow(), 6);
            
            
            txtcNombre.setText(nombre);
            txtcApellidoPaterno.setText(apellido_paterno);
            txtcApellidoMaterno.setText(apellido_materno);
            spncEdad.setValue(edad);
            cmbcSalon.setSelectedItem(salon);
            cmbcStatus.setSelectedItem(status);
            lbcID.setText(ID.toString());
            
            txtcNombre.setEnabled(true);
            txtcApellidoPaterno.setEnabled(true);
            txtcApellidoMaterno.setEnabled(true);
            spncEdad.setEnabled(true);
            cmbcSalon.setEnabled(true);
            cmbcStatus.setEnabled(true);
            btncActualizar.setEnabled(true);
            
        }
    }//GEN-LAST:event_dgvInformacionAlumnoMouseClicked

    private void btncActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncActualizarActionPerformed
        String ID = lbcID.getText();
        String nombres = txtcNombre.getText();
        String apellidoPaterno = txtcApellidoPaterno.getText();
        String apellidoMaterno = txtcApellidoMaterno.getText();
        String edad = spncEdad.getValue().toString();
        String salon = cmbcSalon.getItemAt(cmbcSalon.getSelectedIndex());
        String status = cmbcStatus.getItemAt(cmbcStatus.getSelectedIndex());
        
        if(!nombres.equals("") && !apellidoPaterno.equals("") && !apellidoMaterno.equals("")
            && !edad.equals("") && !salon.equals("")){
            boolean registroExitoso = conexion.actualizarAlumno(ID, nombres, apellidoPaterno, apellidoMaterno, edad, salon, status);
        
            if (registroExitoso){
                JOptionPane.showMessageDialog(this, "El Alumno ha sido modificadodo satisfactorimente", "Éxito", JOptionPane.INFORMATION_MESSAGE);
                llenarTabla();
                limpiarModificar();
                txtcNombre.setEnabled(false);
                txtcApellidoPaterno.setEnabled(false);
                txtcApellidoMaterno.setEnabled(false);
                spncEdad.setEnabled(false);
                cmbcSalon.setEnabled(false);
                cmbcStatus.setEnabled(false);
                btncActualizar.setEnabled(false);
            }else{
                JOptionPane.showMessageDialog(this, "Ha ocurrido un error\nEl Alumno no ha sido modificadodo", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }else{
            JOptionPane.showMessageDialog(this, "Ha ocurrido un error\nDebe de llenar todos los campos", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btncActualizarActionPerformed

    private void btncLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncLimpiarActionPerformed
        limpiarModificar();
    }//GEN-LAST:event_btncLimpiarActionPerformed

    private void btncRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncRegresarActionPerformed
        dialogoConsultaAlumnos.dispose();
        limpiarModificar();
    }//GEN-LAST:event_btncRegresarActionPerformed

    private void txtcNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcNombreKeyTyped
        Character caracter = evt.getKeyChar();

        if(caracter.toString().matches("[^A-za-z á-ñÑ]|_") || (caracter == '\b')){
            evt.consume();
        }
    }//GEN-LAST:event_txtcNombreKeyTyped

    private void txtcApellidoPaternoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcApellidoPaternoKeyTyped
        Character caracter = evt.getKeyChar();

        if(caracter.toString().matches("[^A-za-z á-ñÑ]|_") || (caracter == '\b')){
            evt.consume();
        }
    }//GEN-LAST:event_txtcApellidoPaternoKeyTyped

    private void txtcApellidoMaternoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcApellidoMaternoKeyTyped
        Character caracter = evt.getKeyChar();

        if(caracter.toString().matches("[^A-za-z á-ñÑ]|_") || (caracter == '\b')){
            evt.consume();
        }
    }//GEN-LAST:event_txtcApellidoMaternoKeyTyped
    
    public void limpiarAlta(){
        
        txtNombre.setText("");
        txtApellidoPaterno.setText("");
        txtApellidoMaterno.setText("");
        spnEdad.setValue(9);
        cmbSalon.setSelectedIndex(0);
        
        ResultSet resultados = conexion.consultarBD("SELECT MAX(id_alumno) AS id FROM tabla_alumnos");
        try {
            Integer ID = resultados.getInt("id")+1;
            lbID.setText(ID.toString());
        } catch (SQLException ex) {
            Logger.getLogger(frmAlumnos.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
    
    public void limpiarModificar(){
        txtBusqueda.setText("");
        rdbActivo.setEnabled(false);
        rdbActivo.setSelected(true);
        rdbInactivo.setEnabled(true);
        rdbInactivo.setSelected(false);
        txtcNombre.setText("");
        txtcApellidoPaterno.setText("");
        txtcApellidoMaterno.setText("");
        spncEdad.setValue(9);
        cmbcSalon.setSelectedIndex(0);
        cmbcStatus.setSelectedIndex(0);
        lbcID.setText("número");
        
        btncActualizar.setEnabled(false);
    }
    
    public void llenarTabla(){
        String buscar = "CONCAT(salon, nombre, apellido_paterno, apellido_materno)like '%" + txtBusqueda.getText() + "%' AND status = '"+this.status+"'";

        ResultSet resultados = conexion.consultarTabla("tabla_alumnos", buscar);

        dgvInformacionAlumno.repaint();

        try {
            DefaultTableModel modelo = (DefaultTableModel)dgvInformacionAlumno.getModel();
            modelo.setRowCount(0);
            
            while(resultados.next() == true) {

                int id_alumno = resultados.getInt("id_alumno");
                String nombre = resultados.getString("nombre");
                String apellido_paterno = resultados.getString("apellido_paterno");
                String apellido_materno = resultados.getString("apellido_materno");
                int edad = resultados.getInt("edad");
                String salon = resultados.getString("salon");
                String status = resultados.getString("status");

                modelo.addRow( new Object[] {id_alumno, nombre, apellido_paterno, apellido_materno, edad, salon, status} );
                
            }

            modelo.fireTableDataChanged();
        } catch (SQLException ex) {
            Logger.getLogger(frmAlumnos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmAlumnos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmAlumnos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmAlumnos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmAlumnos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmAlumnos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JButton btncActualizar;
    private javax.swing.JButton btncLimpiar;
    private javax.swing.JButton btncRegresar;
    private javax.swing.JComboBox<String> cmbSalon;
    private javax.swing.JComboBox<String> cmbStatus;
    private javax.swing.JComboBox<String> cmbcSalon;
    private javax.swing.JComboBox<String> cmbcStatus;
    private javax.swing.JTable dgvInformacionAlumno;
    private javax.swing.JDialog dialogoAltasAlumnos;
    private javax.swing.JDialog dialogoAltasUsuarios;
    private javax.swing.JDialog dialogoConsultaAlumnos;
    private javax.swing.JDialog dialogoConsultaUsuarios;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbID;
    private javax.swing.JLabel lbcID;
    private javax.swing.JMenu menuAlumnos;
    private javax.swing.JMenuItem menuItemAltaUsuarios;
    private javax.swing.JMenuItem menuItemAltasAlumnos;
    private javax.swing.JMenuItem menuItemConsulta;
    private javax.swing.JMenuItem menuItemConsultaUsuarios;
    private javax.swing.JMenu menuUsuarios;
    private javax.swing.JRadioButton rdbActivo;
    private javax.swing.JRadioButton rdbInactivo;
    private javax.swing.JSpinner spnEdad;
    private javax.swing.JSpinner spncEdad;
    private javax.swing.JTextField txtApellidoMaterno;
    private javax.swing.JTextField txtApellidoPaterno;
    private javax.swing.JTextField txtBusqueda;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtcApellidoMaterno;
    private javax.swing.JTextField txtcApellidoPaterno;
    private javax.swing.JTextField txtcNombre;
    // End of variables declaration//GEN-END:variables
}
