/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Proyecto;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Image;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author matri
 */
public class frmAlumnos extends javax.swing.JFrame {
    
    String status = "Activo"; 
    int id_usuario;
    Fondo fondo = new Fondo();

    Conexion conexion = new Conexion();
    /**
     * Creates new form frmAlumnos
     */
    public frmAlumnos() {
        this.setContentPane(fondo);
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
        limpiarAltaAlumnos();
        limpiarModificarAlumnos();
    }
    
      public frmAlumnos(int id_usuario) {
          this.id_usuario = id_usuario;
        this.setContentPane(fondo);
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
        limpiarAltaAlumnos();
        limpiarModificarAlumnos();
    }

     //clase Fondo, sirve para ponerle un fondo al jFrame
     class Fondo extends JPanel{    
            private Image img; 
            @Override
            public void paint(Graphics g){   
                img = new ImageIcon(getClass().getResource("/Recursos/oficina.jpg")).getImage();
                g.drawImage(img, 0, 0, getWidth(), getHeight(),this);
                setOpaque(false);
                super.paint(g);
            }//fin paint     
    }//fin fondo
     
     
      public void cerrar(){
        try{
            this.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
            frmMenu menu = new frmMenu(id_usuario);
            menu.setVisible(true);
            this.dispose();
        }
        catch(Exception e){
            e.getMessage();
        }
        
    }//fin cerrar
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dialogoAltasAlumnos = new javax.swing.JDialog();
        jPanel1 = new javax.swing.JPanel();
        txtNombre = new javax.swing.JTextField();
        txtApellidoPaterno = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtApellidoMaterno = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        spnEdad = new javax.swing.JSpinner();
        cmbSalon = new javax.swing.JComboBox<>();
        cmbStatus = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        lbID = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btnRegresarAlumnos_A = new javax.swing.JButton();
        btnAgregarAlumnos_A = new javax.swing.JButton();
        btnLimpiarAlumnos_A = new javax.swing.JButton();
        dialogoConsultaAlumnos = new javax.swing.JDialog();
        jPanel3 = new javax.swing.JPanel();
        txtcNombre = new javax.swing.JTextField();
        txtcApellidoPaterno = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtcApellidoMaterno = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        spncEdad = new javax.swing.JSpinner();
        cmbcSalon = new javax.swing.JComboBox<>();
        cmbcStatus = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        lbcID = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        btnRegresarAlumnos_C = new javax.swing.JButton();
        btnLimpiarAlumnos_C = new javax.swing.JButton();
        txtBusqueda = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        btnActualizarAlumnos_C = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        dgvInformacionAlumno = new javax.swing.JTable();
        rdbActivo = new javax.swing.JRadioButton();
        rdbInactivo = new javax.swing.JRadioButton();
        dialogoAltasUsuarios = new javax.swing.JDialog();
        jPanel5 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        cmbAlumno_A = new javax.swing.JComboBox<>();
        jLabel21 = new javax.swing.JLabel();
        cmbTipo_A = new javax.swing.JComboBox<>();
        txtNombreUsuario_A = new javax.swing.JTextField();
        txtContrasena_A = new javax.swing.JPasswordField();
        jLabel22 = new javax.swing.JLabel();
        btnAgregarUsuarios_A = new javax.swing.JButton();
        btnLimpiarUsuarios_A = new javax.swing.JButton();
        btnRegresarUsuarios_C = new javax.swing.JButton();
        dialogoConsultaUsuarios = new javax.swing.JDialog();
        jPanel6 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        cmbAlumno_C = new javax.swing.JComboBox<>();
        jLabel26 = new javax.swing.JLabel();
        cmbTipo_C = new javax.swing.JComboBox<>();
        txtNombreUsuario_C = new javax.swing.JTextField();
        txtContrasena_C = new javax.swing.JPasswordField();
        jLabel27 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        btnLimpiarUsuarios_C = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        dgvInformacionUsuarios = new javax.swing.JTable();
        txtBusquedaUsuarios = new javax.swing.JTextField();
        rdbActivoUsuarios = new javax.swing.JRadioButton();
        rdbInactivoUsuarios = new javax.swing.JRadioButton();
        jLabel28 = new javax.swing.JLabel();
        menuEmergente = new javax.swing.JPopupMenu();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuAlumnos = new javax.swing.JMenu();
        menuItemAltasAlumnos = new javax.swing.JMenuItem();
        menuItemConsulta = new javax.swing.JMenuItem();
        menuUsuarios = new javax.swing.JMenu();
        menuItemAltaUsuarios = new javax.swing.JMenuItem();
        menuItemConsultaUsuarios = new javax.swing.JMenuItem();

        dialogoAltasAlumnos.setTitle("Alta de alumnos");
        dialogoAltasAlumnos.setModal(true);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        txtNombre.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        txtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreKeyTyped(evt);
            }
        });

        txtApellidoPaterno.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        txtApellidoPaterno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtApellidoPaternoKeyTyped(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        jLabel1.setText("Nombre(s)");

        jLabel2.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        jLabel2.setText("Apellido Paterno");

        jLabel3.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        jLabel3.setText("Apellido Materno");

        txtApellidoMaterno.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        txtApellidoMaterno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtApellidoMaternoKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txtApellidoPaterno, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
                    .addComponent(txtNombre)
                    .addComponent(txtApellidoMaterno))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtApellidoPaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtApellidoMaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26))
        );

        jPanel2.setBackground(new java.awt.Color(255, 204, 204));

        jLabel4.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        jLabel4.setText("Edad");

        jLabel5.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        jLabel5.setText("Salón");

        jLabel6.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        jLabel6.setText("Status");

        spnEdad.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        spnEdad.setModel(new javax.swing.SpinnerNumberModel(9, 8, 100, 1));

        cmbSalon.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        cmbSalon.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "3A", "3B", "3C", "4A", "4B", "4C" }));

        cmbStatus.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        cmbStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Activo", "Inactivo" }));
        cmbStatus.setEnabled(false);

        jLabel7.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        jLabel7.setText("Id_alumno");

        lbID.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        lbID.setText("0");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(spnEdad))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(cmbSalon, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(cmbStatus, 0, 109, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(lbID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(spnEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(lbID))
                .addGap(66, 66, 66)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cmbSalon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(cmbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel9.setFont(new java.awt.Font("Century Schoolbook", 1, 24)); // NOI18N
        jLabel9.setText("ALTA DE ALUMNOS");

        btnRegresarAlumnos_A.setBackground(new java.awt.Color(244, 186, 186));
        btnRegresarAlumnos_A.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        btnRegresarAlumnos_A.setText("Regresar");
        btnRegresarAlumnos_A.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarAlumnos_AActionPerformed(evt);
            }
        });

        btnAgregarAlumnos_A.setBackground(new java.awt.Color(186, 244, 185));
        btnAgregarAlumnos_A.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        btnAgregarAlumnos_A.setText("Agregar");
        btnAgregarAlumnos_A.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarAlumnos_AActionPerformed(evt);
            }
        });

        btnLimpiarAlumnos_A.setBackground(new java.awt.Color(181, 226, 255));
        btnLimpiarAlumnos_A.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        btnLimpiarAlumnos_A.setText("Limpiar");
        btnLimpiarAlumnos_A.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarAlumnos_AActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dialogoAltasAlumnosLayout = new javax.swing.GroupLayout(dialogoAltasAlumnos.getContentPane());
        dialogoAltasAlumnos.getContentPane().setLayout(dialogoAltasAlumnosLayout);
        dialogoAltasAlumnosLayout.setHorizontalGroup(
            dialogoAltasAlumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dialogoAltasAlumnosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addGap(251, 251, 251))
            .addGroup(dialogoAltasAlumnosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dialogoAltasAlumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dialogoAltasAlumnosLayout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(dialogoAltasAlumnosLayout.createSequentialGroup()
                        .addComponent(btnRegresarAlumnos_A, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnLimpiarAlumnos_A, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(btnAgregarAlumnos_A, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        dialogoAltasAlumnosLayout.setVerticalGroup(
            dialogoAltasAlumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogoAltasAlumnosLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addGroup(dialogoAltasAlumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addGroup(dialogoAltasAlumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegresarAlumnos_A, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAgregarAlumnos_A, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLimpiarAlumnos_A, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        dialogoConsultaAlumnos.setTitle("Consulta de alumnos");
        dialogoConsultaAlumnos.setModal(true);

        jPanel3.setBackground(new java.awt.Color(204, 204, 255));

        txtcNombre.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        txtcNombre.setEnabled(false);
        txtcNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtcNombreKeyTyped(evt);
            }
        });

        txtcApellidoPaterno.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        txtcApellidoPaterno.setEnabled(false);
        txtcApellidoPaterno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtcApellidoPaternoKeyTyped(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        jLabel10.setText("Nombre(s)");

        jLabel11.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        jLabel11.setText("Apellido Paterno");

        jLabel12.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        jLabel12.setText("Apellido Materno");

        txtcApellidoMaterno.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        txtcApellidoMaterno.setEnabled(false);
        txtcApellidoMaterno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtcApellidoMaternoKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txtcApellidoPaterno, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
                    .addComponent(txtcNombre)
                    .addComponent(txtcApellidoMaterno))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtcNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(43, 43, 43)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtcApellidoPaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtcApellidoMaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26))
        );

        jPanel4.setBackground(new java.awt.Color(255, 204, 204));

        jLabel13.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        jLabel13.setText("Edad");

        jLabel14.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        jLabel14.setText("Salón");

        jLabel15.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        jLabel15.setText("Status");

        spncEdad.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        spncEdad.setModel(new javax.swing.SpinnerNumberModel(9, 8, 100, 1));
        spncEdad.setEnabled(false);

        cmbcSalon.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        cmbcSalon.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "3A", "3B", "3C", "4A", "4B", "4C" }));
        cmbcSalon.setEnabled(false);

        cmbcStatus.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        cmbcStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Activo", "Inactivo" }));
        cmbcStatus.setEnabled(false);

        jLabel16.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        jLabel16.setText("Id_alumno");

        lbcID.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        lbcID.setText("numero");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGap(18, 18, 18)
                        .addComponent(spncEdad))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addGap(18, 18, 18)
                        .addComponent(cmbcSalon, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addGap(18, 18, 18)
                        .addComponent(cmbcStatus, 0, 108, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addGap(18, 18, 18)
                        .addComponent(lbcID)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(5, 5, 5))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(spncEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16)
                    .addComponent(lbcID))
                .addGap(66, 66, 66)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(cmbcSalon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(cmbcStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(56, Short.MAX_VALUE))
        );

        jLabel18.setFont(new java.awt.Font("Century Schoolbook", 1, 24)); // NOI18N
        jLabel18.setText("CONSULTA DE ALUMNOS");

        btnRegresarAlumnos_C.setBackground(new java.awt.Color(244, 186, 186));
        btnRegresarAlumnos_C.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        btnRegresarAlumnos_C.setText("Regresar");
        btnRegresarAlumnos_C.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarAlumnos_CActionPerformed(evt);
            }
        });

        btnLimpiarAlumnos_C.setBackground(new java.awt.Color(181, 226, 255));
        btnLimpiarAlumnos_C.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        btnLimpiarAlumnos_C.setText("Limpiar");
        btnLimpiarAlumnos_C.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarAlumnos_CActionPerformed(evt);
            }
        });

        txtBusqueda.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        txtBusqueda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtBusquedaKeyTyped(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        jLabel19.setText("Búsqueda de alumnos:");

        btnActualizarAlumnos_C.setBackground(new java.awt.Color(186, 244, 185));
        btnActualizarAlumnos_C.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        btnActualizarAlumnos_C.setText("Actualizar datos");
        btnActualizarAlumnos_C.setEnabled(false);
        btnActualizarAlumnos_C.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarAlumnos_CActionPerformed(evt);
            }
        });

        dgvInformacionAlumno.setBackground(new java.awt.Color(255, 255, 204));
        dgvInformacionAlumno.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "nombre", "Apellido Paterno", "Apellido Materno", "Edad", "Salón", "status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        dgvInformacionAlumno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dgvInformacionAlumnoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(dgvInformacionAlumno);

        rdbActivo.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        rdbActivo.setSelected(true);
        rdbActivo.setText("Activo");
        rdbActivo.setEnabled(false);
        rdbActivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbActivoActionPerformed(evt);
            }
        });

        rdbInactivo.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        rdbInactivo.setText("Inactivo");
        rdbInactivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbInactivoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dialogoConsultaAlumnosLayout = new javax.swing.GroupLayout(dialogoConsultaAlumnos.getContentPane());
        dialogoConsultaAlumnos.getContentPane().setLayout(dialogoConsultaAlumnosLayout);
        dialogoConsultaAlumnosLayout.setHorizontalGroup(
            dialogoConsultaAlumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogoConsultaAlumnosLayout.createSequentialGroup()
                .addGap(236, 236, 236)
                .addComponent(jLabel18))
            .addGroup(dialogoConsultaAlumnosLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel19)
                .addGap(18, 18, 18)
                .addComponent(txtBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(rdbActivo)
                .addGap(34, 34, 34)
                .addComponent(rdbInactivo))
            .addGroup(dialogoConsultaAlumnosLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 740, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(dialogoConsultaAlumnosLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(dialogoConsultaAlumnosLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(btnRegresarAlumnos_C, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(330, 330, 330)
                .addComponent(btnLimpiarAlumnos_C, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(btnActualizarAlumnos_C, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        dialogoConsultaAlumnosLayout.setVerticalGroup(
            dialogoConsultaAlumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogoConsultaAlumnosLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel18)
                .addGap(17, 17, 17)
                .addGroup(dialogoConsultaAlumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dialogoConsultaAlumnosLayout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel19))
                    .addGroup(dialogoConsultaAlumnosLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(txtBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(rdbActivo)
                    .addComponent(rdbInactivo))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(dialogoConsultaAlumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(dialogoConsultaAlumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnRegresarAlumnos_C, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLimpiarAlumnos_C, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnActualizarAlumnos_C, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        dialogoAltasUsuarios.setModal(true);

        jPanel5.setBackground(new java.awt.Color(142, 216, 253));

        jLabel8.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        jLabel8.setText("Nombre de usuario");

        jLabel17.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        jLabel17.setText("Contraseña");

        jLabel20.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        jLabel20.setText("Tipo de usuario");

        cmbAlumno_A.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N

        jLabel21.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        jLabel21.setText("Alumno asociado");

        cmbTipo_A.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        cmbTipo_A.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Alumno", "Administrador" }));

        txtNombreUsuario_A.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N

        txtContrasena_A.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtNombreUsuario_A)
                    .addComponent(txtContrasena_A, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE))
                .addGap(36, 36, 36)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel20)
                    .addComponent(jLabel21))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cmbAlumno_A, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmbTipo_A, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel20)
                    .addComponent(txtNombreUsuario_A, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbTipo_A, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(cmbAlumno_A, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21)
                    .addComponent(txtContrasena_A, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(52, Short.MAX_VALUE))
        );

        jLabel22.setFont(new java.awt.Font("Century Schoolbook", 1, 24)); // NOI18N
        jLabel22.setText("ALTA DE USUARIOS");

        btnAgregarUsuarios_A.setBackground(new java.awt.Color(204, 255, 204));
        btnAgregarUsuarios_A.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        btnAgregarUsuarios_A.setText("Agregar");

        btnLimpiarUsuarios_A.setBackground(new java.awt.Color(153, 204, 255));
        btnLimpiarUsuarios_A.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        btnLimpiarUsuarios_A.setText("Limpiar");
        btnLimpiarUsuarios_A.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarUsuarios_AActionPerformed(evt);
            }
        });

        btnRegresarUsuarios_C.setBackground(new java.awt.Color(255, 204, 204));
        btnRegresarUsuarios_C.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        btnRegresarUsuarios_C.setText("Regresar");

        javax.swing.GroupLayout dialogoAltasUsuariosLayout = new javax.swing.GroupLayout(dialogoAltasUsuarios.getContentPane());
        dialogoAltasUsuarios.getContentPane().setLayout(dialogoAltasUsuariosLayout);
        dialogoAltasUsuariosLayout.setHorizontalGroup(
            dialogoAltasUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogoAltasUsuariosLayout.createSequentialGroup()
                .addGroup(dialogoAltasUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dialogoAltasUsuariosLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dialogoAltasUsuariosLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnRegresarUsuarios_C, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnLimpiarUsuarios_A, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(btnAgregarUsuarios_A, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dialogoAltasUsuariosLayout.createSequentialGroup()
                .addGap(211, 211, 211)
                .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(205, 205, 205))
        );
        dialogoAltasUsuariosLayout.setVerticalGroup(
            dialogoAltasUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogoAltasUsuariosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel22)
                .addGap(28, 28, 28)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addGroup(dialogoAltasUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregarUsuarios_A, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLimpiarUsuarios_A, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRegresarUsuarios_C, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        dialogoConsultaUsuarios.setModal(true);

        jPanel6.setBackground(new java.awt.Color(142, 216, 253));

        jLabel23.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        jLabel23.setText("Nombre de usuario");

        jLabel24.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        jLabel24.setText("Contraseña");

        jLabel25.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        jLabel25.setText("Tipo de usuario");

        cmbAlumno_C.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N

        jLabel26.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        jLabel26.setText("Alumno asociado");

        cmbTipo_C.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        cmbTipo_C.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Alumno", "Administrador" }));

        txtNombreUsuario_C.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N

        txtContrasena_C.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel23)
                    .addComponent(jLabel24))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtNombreUsuario_C, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                    .addComponent(txtContrasena_C))
                .addGap(36, 36, 36)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel25)
                    .addComponent(jLabel26))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cmbTipo_C, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbAlumno_C, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(jLabel25)
                    .addComponent(txtNombreUsuario_C, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbTipo_C, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(cmbAlumno_C, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel26)
                    .addComponent(txtContrasena_C, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jLabel27.setFont(new java.awt.Font("Century Schoolbook", 1, 24)); // NOI18N
        jLabel27.setText("CONSULTA DE USUARIOS");

        jButton4.setBackground(new java.awt.Color(204, 255, 204));
        jButton4.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        jButton4.setText("Actualizar datos");
        jButton4.setEnabled(false);

        btnLimpiarUsuarios_C.setBackground(new java.awt.Color(153, 204, 255));
        btnLimpiarUsuarios_C.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        btnLimpiarUsuarios_C.setText("Limpiar");

        jButton6.setBackground(new java.awt.Color(255, 204, 204));
        jButton6.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        jButton6.setText("Regresar");

        dgvInformacionUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(dgvInformacionUsuarios);

        txtBusquedaUsuarios.setFont(new java.awt.Font("Century Schoolbook", 1, 12)); // NOI18N

        rdbActivoUsuarios.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        rdbActivoUsuarios.setSelected(true);
        rdbActivoUsuarios.setText("Activo");

        rdbInactivoUsuarios.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        rdbInactivoUsuarios.setText("Inactivo");

        jLabel28.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        jLabel28.setText("Búsqueda de usuarios");

        javax.swing.GroupLayout dialogoConsultaUsuariosLayout = new javax.swing.GroupLayout(dialogoConsultaUsuarios.getContentPane());
        dialogoConsultaUsuarios.getContentPane().setLayout(dialogoConsultaUsuariosLayout);
        dialogoConsultaUsuariosLayout.setHorizontalGroup(
            dialogoConsultaUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogoConsultaUsuariosLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(dialogoConsultaUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dialogoConsultaUsuariosLayout.createSequentialGroup()
                        .addGroup(dialogoConsultaUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(dialogoConsultaUsuariosLayout.createSequentialGroup()
                                .addGap(153, 153, 153)
                                .addComponent(jLabel27, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(dialogoConsultaUsuariosLayout.createSequentialGroup()
                                .addComponent(jLabel28)
                                .addGap(10, 10, 10)
                                .addComponent(txtBusquedaUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(rdbActivoUsuarios)
                                .addGap(2, 2, 2)))
                        .addGap(27, 27, 27)
                        .addComponent(rdbInactivoUsuarios)
                        .addGap(53, 53, 53))
                    .addGroup(dialogoConsultaUsuariosLayout.createSequentialGroup()
                        .addGroup(dialogoConsultaUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 640, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 640, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(dialogoConsultaUsuariosLayout.createSequentialGroup()
                                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(240, 240, 240)
                                .addComponent(btnLimpiarUsuarios_C, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(20, 20, 20))))
        );
        dialogoConsultaUsuariosLayout.setVerticalGroup(
            dialogoConsultaUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogoConsultaUsuariosLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel27)
                .addGap(30, 30, 30)
                .addGroup(dialogoConsultaUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel28)
                    .addComponent(txtBusquedaUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(dialogoConsultaUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(rdbInactivoUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(rdbActivoUsuarios)))
                .addGap(30, 30, 30)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addGroup(dialogoConsultaUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLimpiarUsuarios_C, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        menuEmergente.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jMenu1.setText("Alumnos");

        jMenuItem1.setText("Alta de alumnos");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem3.setText("Consulta de alumnos");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        menuEmergente.add(jMenu1);

        jMenu2.setText("Usuarios");

        jMenuItem2.setText("Alta de usuarios");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuItem4.setText("Consulta de usuarios");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem4);

        menuEmergente.add(jMenu2);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Administrar Alumnos y Usuarios");
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        menuAlumnos.setText("Alumnos");

        menuItemAltasAlumnos.setText("Alta de alumnos");
        menuItemAltasAlumnos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemAltasAlumnosActionPerformed(evt);
            }
        });
        menuAlumnos.add(menuItemAltasAlumnos);

        menuItemConsulta.setText("Consulta de alumnos");
        menuItemConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemConsultaActionPerformed(evt);
            }
        });
        menuAlumnos.add(menuItemConsulta);

        jMenuBar1.add(menuAlumnos);

        menuUsuarios.setText("Usuarios");

        menuItemAltaUsuarios.setText("Alta de usuarios");
        menuItemAltaUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemAltaUsuariosActionPerformed(evt);
            }
        });
        menuUsuarios.add(menuItemAltaUsuarios);

        menuItemConsultaUsuarios.setText("Consulta de usuarios");
        menuItemConsultaUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemConsultaUsuariosActionPerformed(evt);
            }
        });
        menuUsuarios.add(menuItemConsultaUsuarios);

        jMenuBar1.add(menuUsuarios);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 332, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 261, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuItemAltasAlumnosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemAltasAlumnosActionPerformed
        dialogoAltasAlumnos.getContentPane().setBackground(Color.white);
        dialogoAltasAlumnos.setSize(775,409);
        dialogoAltasAlumnos.setVisible(true);
    }//GEN-LAST:event_menuItemAltasAlumnosActionPerformed

    private void rdbInactivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbInactivoActionPerformed
        this.status = "Inactivo";
        rdbActivo.setSelected(false);
        rdbActivo.setEnabled(true);
        rdbInactivo.setEnabled(false);
        llenarTabla();
    }//GEN-LAST:event_rdbInactivoActionPerformed

    private void menuItemConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemConsultaActionPerformed
        dialogoConsultaAlumnos.getContentPane().setBackground(Color.white);
        dialogoConsultaAlumnos.setSize(795,630);
        dialogoConsultaAlumnos.setVisible(true);
    }//GEN-LAST:event_menuItemConsultaActionPerformed

    private void btnAgregarAlumnos_AActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarAlumnos_AActionPerformed
        String nombres = txtNombre.getText();
        String apellidoPaterno = txtApellidoPaterno.getText();
        String apellidoMaterno = txtApellidoMaterno.getText();
        String edad = spnEdad.getValue().toString();
        String salon = cmbSalon.getItemAt(cmbSalon.getSelectedIndex());
        
        if(!nombres.equals("") && !apellidoPaterno.equals("") && !apellidoMaterno.equals("")
            && !edad.equals("") && !salon.equals("")){
            boolean registroExitoso = conexion.registrarAlumno(nombres, apellidoPaterno, apellidoMaterno, edad, salon);
           
       /*     //lo que está en comentarios debería estar al registrar un usuario no un alumno un saludo
            boolean puntaje = conexion.actualizarBD("INSERT INTO tabla_puntajes (memorama, id_usuario) Values (0, "+id_usuario+")");
            boolean trivia = conexion.actualizarBD("INSERT INTO puntaje_trivia (puntaje, id_materia, id_puntajes) VALUES (0, 1,"+id_usuario+"), (0, 2,"+id_usuario+"), (0, 3,"+id_usuario+"), (0, 4,"+id_usuario+")");
        */
            if (registroExitoso){
                JOptionPane.showMessageDialog(this, "El Alumno ha sido registrado satisfactorimente", "Éxito", JOptionPane.INFORMATION_MESSAGE);
                limpiarAltaAlumnos();
            }else{
                JOptionPane.showMessageDialog(this, "Ha ocurrido un error\nEl Alumno no ha sido registrado", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }else{
            JOptionPane.showMessageDialog(this, "Ha ocurrido un error\nDebe de llenar todos los campos", "Error", JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_btnAgregarAlumnos_AActionPerformed

    private void txtNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKeyTyped
        Character caracter = evt.getKeyChar();

        if(caracter.toString().matches("[^A-za-z á-ñÑ]|_") || (caracter == '\b')){
            evt.consume();
        }
    }//GEN-LAST:event_txtNombreKeyTyped

    private void txtApellidoPaternoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtApellidoPaternoKeyTyped
        Character caracter = evt.getKeyChar();

        if(caracter.toString().matches("[^A-za-z á-ñÑ]|_") || (caracter == '\b')){
            evt.consume();
        }
    }//GEN-LAST:event_txtApellidoPaternoKeyTyped

    private void txtApellidoMaternoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtApellidoMaternoKeyTyped
        Character caracter = evt.getKeyChar();

        if(caracter.toString().matches("[^A-za-z á-ñÑ]|_") || (caracter == '\b')){
            evt.consume();
        }
    }//GEN-LAST:event_txtApellidoMaternoKeyTyped

    private void btnLimpiarAlumnos_AActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarAlumnos_AActionPerformed
        limpiarAltaAlumnos();
    }//GEN-LAST:event_btnLimpiarAlumnos_AActionPerformed

    private void btnRegresarAlumnos_AActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarAlumnos_AActionPerformed
        dialogoAltasAlumnos.dispose();
        limpiarAltaAlumnos();
    }//GEN-LAST:event_btnRegresarAlumnos_AActionPerformed

    private void rdbActivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbActivoActionPerformed
        this.status = "Activo";
        rdbInactivo.setSelected(false);
        rdbInactivo.setEnabled(true);
        rdbActivo.setEnabled(false);
        llenarTabla();
    }//GEN-LAST:event_rdbActivoActionPerformed

    private void txtBusquedaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBusquedaKeyTyped
        llenarTabla();
    }//GEN-LAST:event_txtBusquedaKeyTyped

    private void dgvInformacionAlumnoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dgvInformacionAlumnoMouseClicked
        if (dgvInformacionAlumno.getSelectedRow() != -1) {
            Integer ID = (Integer) dgvInformacionAlumno.getModel().getValueAt(dgvInformacionAlumno.getSelectedRow(), 0);
            String nombre = (String) dgvInformacionAlumno.getModel().getValueAt(dgvInformacionAlumno.getSelectedRow(), 1);
            String apellido_paterno = (String) dgvInformacionAlumno.getModel().getValueAt(dgvInformacionAlumno.getSelectedRow(), 2);
            String apellido_materno = (String) dgvInformacionAlumno.getModel().getValueAt(dgvInformacionAlumno.getSelectedRow(), 3);
            int edad = (int) dgvInformacionAlumno.getModel().getValueAt(dgvInformacionAlumno.getSelectedRow(), 4);
            String salon = (String) dgvInformacionAlumno.getModel().getValueAt(dgvInformacionAlumno.getSelectedRow(), 5);
            String status = (String) dgvInformacionAlumno.getModel().getValueAt(dgvInformacionAlumno.getSelectedRow(), 6);
            
            
            txtcNombre.setText(nombre);
            txtcApellidoPaterno.setText(apellido_paterno);
            txtcApellidoMaterno.setText(apellido_materno);
            spncEdad.setValue(edad);
            cmbcSalon.setSelectedItem(salon);
            cmbcStatus.setSelectedItem(status);
            lbcID.setText(ID.toString());
            
            txtcNombre.setEnabled(true);
            txtcApellidoPaterno.setEnabled(true);
            txtcApellidoMaterno.setEnabled(true);
            spncEdad.setEnabled(true);
            cmbcSalon.setEnabled(true);
            cmbcStatus.setEnabled(true);
            btnActualizarAlumnos_C.setEnabled(true);
            
        }
    }//GEN-LAST:event_dgvInformacionAlumnoMouseClicked

    private void btnActualizarAlumnos_CActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarAlumnos_CActionPerformed
        String ID = lbcID.getText();
        String nombres = txtcNombre.getText();
        String apellidoPaterno = txtcApellidoPaterno.getText();
        String apellidoMaterno = txtcApellidoMaterno.getText();
        String edad = spncEdad.getValue().toString();
        String salon = cmbcSalon.getItemAt(cmbcSalon.getSelectedIndex());
        String status = cmbcStatus.getItemAt(cmbcStatus.getSelectedIndex());
        
        if(!nombres.equals("") && !apellidoPaterno.equals("") && !apellidoMaterno.equals("")
            && !edad.equals("") && !salon.equals("")){
            boolean registroExitoso = conexion.actualizarAlumno(ID, nombres, apellidoPaterno, apellidoMaterno, edad, salon, status);
        
            if (registroExitoso){
                JOptionPane.showMessageDialog(this, "El Alumno ha sido modificadodo satisfactorimente", "Éxito", JOptionPane.INFORMATION_MESSAGE);
                llenarTabla();
                limpiarModificarAlumnos();
                txtcNombre.setEnabled(false);
                txtcApellidoPaterno.setEnabled(false);
                txtcApellidoMaterno.setEnabled(false);
                spncEdad.setEnabled(false);
                cmbcSalon.setEnabled(false);
                cmbcStatus.setEnabled(false);
                btnActualizarAlumnos_C.setEnabled(false);
            }else{
                JOptionPane.showMessageDialog(this, "Ha ocurrido un error\nEl Alumno no ha sido modificadodo", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }else{
            JOptionPane.showMessageDialog(this, "Ha ocurrido un error\nDebe de llenar todos los campos", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnActualizarAlumnos_CActionPerformed

    private void btnLimpiarAlumnos_CActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarAlumnos_CActionPerformed
        limpiarModificarAlumnos();
    }//GEN-LAST:event_btnLimpiarAlumnos_CActionPerformed

    private void btnRegresarAlumnos_CActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarAlumnos_CActionPerformed
        dialogoConsultaAlumnos.dispose();
        limpiarModificarAlumnos();
    }//GEN-LAST:event_btnRegresarAlumnos_CActionPerformed

    private void menuItemAltaUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemAltaUsuariosActionPerformed
        
        dialogoAltasUsuarios.getContentPane().setBackground(Color.white);
        dialogoAltasUsuarios.setSize(700,410);
        dialogoAltasUsuarios.setVisible(true);
        
    }//GEN-LAST:event_menuItemAltaUsuariosActionPerformed

    private void menuItemConsultaUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemConsultaUsuariosActionPerformed
        
        dialogoConsultaUsuarios.getContentPane().setBackground(Color.white);
        dialogoConsultaUsuarios.setSize(700,550);
        dialogoConsultaUsuarios.setVisible(true);
        
    }//GEN-LAST:event_menuItemConsultaUsuariosActionPerformed

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        
          menuEmergente.show(this , evt.getX(), evt.getY());  
        
    }//GEN-LAST:event_formMousePressed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
      //Alta de alumnos
      menuItemAltasAlumnosActionPerformed(evt);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
     //Consulta de alumnos
     menuItemConsultaActionPerformed(evt);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        //Alta de usuarios
        menuItemAltaUsuariosActionPerformed(evt);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // Consulta de usuarios
        menuItemConsultaUsuariosActionPerformed(evt);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
       
        cerrar();
    }//GEN-LAST:event_formWindowClosing
    private void txtcNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcNombreKeyTyped
        Character caracter = evt.getKeyChar();

        if(caracter.toString().matches("[^A-za-z á-ñÑ]|_") || (caracter == '\b')){
            evt.consume();
        }
    }//GEN-LAST:event_txtcNombreKeyTyped

    private void txtcApellidoPaternoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcApellidoPaternoKeyTyped
        Character caracter = evt.getKeyChar();

        if(caracter.toString().matches("[^A-za-z á-ñÑ]|_") || (caracter == '\b')){
            evt.consume();
        }
    }//GEN-LAST:event_txtcApellidoPaternoKeyTyped

    private void txtcApellidoMaternoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcApellidoMaternoKeyTyped
        Character caracter = evt.getKeyChar();

        if(caracter.toString().matches("[^A-za-z á-ñÑ]|_") || (caracter == '\b')){
            evt.consume();
        }
    }//GEN-LAST:event_txtcApellidoMaternoKeyTyped

    private void btnLimpiarUsuarios_AActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarUsuarios_AActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLimpiarUsuarios_AActionPerformed
    
    public void limpiarAltaAlumnos(){
        
        txtNombre.setText("");
        txtApellidoPaterno.setText("");
        txtApellidoMaterno.setText("");
        spnEdad.setValue(9);
        cmbSalon.setSelectedIndex(0);
        
        ResultSet resultados = conexion.consultarBD("SELECT MAX(id_alumno) AS id FROM tabla_alumnos");
        try {
            Integer ID = resultados.getInt("id")+1;
            lbID.setText(ID.toString());
        } catch (SQLException ex) {
            Logger.getLogger(frmAlumnos.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
    
    public void limpiarModificarAlumnos(){
        txtBusqueda.setText("");
        rdbActivo.setEnabled(false);
        rdbActivo.setSelected(true);
        rdbInactivo.setEnabled(true);
        rdbInactivo.setSelected(false);
        txtcNombre.setText("");
        txtcApellidoPaterno.setText("");
        txtcApellidoMaterno.setText("");
        spncEdad.setValue(9);
        cmbcSalon.setSelectedIndex(0);
        cmbcStatus.setSelectedIndex(0);
        lbcID.setText("número");
        
        btnActualizarAlumnos_C.setEnabled(false);
    }
    
    public void llenarTabla(){
        String buscar = "CONCAT(salon, nombre, apellido_paterno, apellido_materno)like '%" + txtBusqueda.getText() + "%' AND status = '"+this.status+"'";

        ResultSet resultados = conexion.consultarTabla("tabla_alumnos", buscar);

        dgvInformacionAlumno.repaint();

        try {
            DefaultTableModel modelo = (DefaultTableModel)dgvInformacionAlumno.getModel();
            modelo.setRowCount(0);
            
            while(resultados.next() == true) {

                int id_alumno = resultados.getInt("id_alumno");
                String nombre = resultados.getString("nombre");
                String apellido_paterno = resultados.getString("apellido_paterno");
                String apellido_materno = resultados.getString("apellido_materno");
                int edad = resultados.getInt("edad");
                String salon = resultados.getString("salon");
                String status = resultados.getString("status");

                modelo.addRow( new Object[] {id_alumno, nombre, apellido_paterno, apellido_materno, edad, salon, status} );
                
            }

            modelo.fireTableDataChanged();
        } catch (SQLException ex) {
            Logger.getLogger(frmAlumnos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmAlumnos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmAlumnos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmAlumnos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmAlumnos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmAlumnos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizarAlumnos_C;
    private javax.swing.JButton btnAgregarAlumnos_A;
    private javax.swing.JButton btnAgregarUsuarios_A;
    private javax.swing.JButton btnLimpiarAlumnos_A;
    private javax.swing.JButton btnLimpiarAlumnos_C;
    private javax.swing.JButton btnLimpiarUsuarios_A;
    private javax.swing.JButton btnLimpiarUsuarios_C;
    private javax.swing.JButton btnRegresarAlumnos_A;
    private javax.swing.JButton btnRegresarAlumnos_C;
    private javax.swing.JButton btnRegresarUsuarios_C;
    private javax.swing.JComboBox<String> cmbAlumno_A;
    private javax.swing.JComboBox<String> cmbAlumno_C;
    private javax.swing.JComboBox<String> cmbSalon;
    private javax.swing.JComboBox<String> cmbStatus;
    private javax.swing.JComboBox<String> cmbTipo_A;
    private javax.swing.JComboBox<String> cmbTipo_C;
    private javax.swing.JComboBox<String> cmbcSalon;
    private javax.swing.JComboBox<String> cmbcStatus;
    private javax.swing.JTable dgvInformacionAlumno;
    private javax.swing.JTable dgvInformacionUsuarios;
    private javax.swing.JDialog dialogoAltasAlumnos;
    private javax.swing.JDialog dialogoAltasUsuarios;
    private javax.swing.JDialog dialogoConsultaAlumnos;
    private javax.swing.JDialog dialogoConsultaUsuarios;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbID;
    private javax.swing.JLabel lbcID;
    private javax.swing.JMenu menuAlumnos;
    private javax.swing.JPopupMenu menuEmergente;
    private javax.swing.JMenuItem menuItemAltaUsuarios;
    private javax.swing.JMenuItem menuItemAltasAlumnos;
    private javax.swing.JMenuItem menuItemConsulta;
    private javax.swing.JMenuItem menuItemConsultaUsuarios;
    private javax.swing.JMenu menuUsuarios;
    private javax.swing.JRadioButton rdbActivo;
    private javax.swing.JRadioButton rdbActivoUsuarios;
    private javax.swing.JRadioButton rdbInactivo;
    private javax.swing.JRadioButton rdbInactivoUsuarios;
    private javax.swing.JSpinner spnEdad;
    private javax.swing.JSpinner spncEdad;
    private javax.swing.JTextField txtApellidoMaterno;
    private javax.swing.JTextField txtApellidoPaterno;
    private javax.swing.JTextField txtBusqueda;
    private javax.swing.JTextField txtBusquedaUsuarios;
    private javax.swing.JPasswordField txtContrasena_A;
    private javax.swing.JPasswordField txtContrasena_C;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNombreUsuario_A;
    private javax.swing.JTextField txtNombreUsuario_C;
    private javax.swing.JTextField txtcApellidoMaterno;
    private javax.swing.JTextField txtcApellidoPaterno;
    private javax.swing.JTextField txtcNombre;
    // End of variables declaration//GEN-END:variables
}
