/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Proyecto;

import javax.swing.*;
import javax.swing.JPanel;
import javax.swing.ImageIcon;
import java.awt.*;

/**
 *
 * @author matri
 */
public class frmBiblioteca extends javax.swing.JFrame {

    Fondo fondo = new Fondo();
    /**
     * Creates new form frmPizarra
     */
    public frmBiblioteca() {
        
        this.setContentPane(fondo);
        initComponents();
        inicializarComponentes();
       
        
    }//fin constructor
    
    //método para hacer modificaciones de los componentes al inicializar la forma
    public void inicializarComponentes(){
        
        btnEspanol.setOpaque(false);
        btnGeografia.setOpaque(false);
        btnVolver.setOpaque(false);
        btnCiencias.setOpaque(false);
        btnHistoria.setOpaque(false);
        
        btnEspanol.setBorderPainted(false);
        btnGeografia.setBorderPainted(false);
        btnVolver.setBorderPainted(false);
        btnCiencias.setBorderPainted(false);
        btnHistoria.setBorderPainted(false);
        
        btnEspanol.setContentAreaFilled(false);
        btnGeografia.setContentAreaFilled(false);
        btnVolver.setContentAreaFilled(false);
        btnCiencias.setContentAreaFilled(false);
        btnHistoria.setContentAreaFilled(false);
        
        panelLouie.setOpaque(false);
        
        desaparecerDialogo();
    }//fin inicializar componentes
    
    class Fondo extends JPanel{    
                private Image img; 
                @Override
                public void paint(Graphics g){   
                    img = new ImageIcon(getClass().getResource("/Recursos/biblioteca.jpg")).getImage();
                    g.drawImage(img, 0, 0, getWidth(), getHeight(),this);
                    setOpaque(false);
                    super.paint(g);
                }//fin paint     
        }//fin fondo
    
    
    public void cerrar(){
        try{
            this.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
            frmMenu menu = new frmMenu();
            menu.setVisible(true);
            this.dispose();
        }
        catch(Exception e){
            e.getMessage();
        }
        
    }//fin cerrar
    
    //desaparece el Dialogo de Louie
    public void desaparecerDialogo(){
        
        etiDialogo.setVisible(false);
        txtAreaTexto.setVisible(false);
        jScrollPane2.setVisible(false);
        
    }//fin desaparecerDialogo
    
    
    public void aparecerDialogo(){
        
         etiDialogo.setVisible(true);
        jScrollPane2.setVisible(true);
        txtAreaTexto.setVisible(true);
        
    }//fin aparecerDialogo
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnVolver = new javax.swing.JButton();
        etiLibroRojo = new javax.swing.JLabel();
        etiLibroAzul = new javax.swing.JLabel();
        etiLibroAmarillo = new javax.swing.JLabel();
        etiLibroVerde = new javax.swing.JLabel();
        btnGeografia = new javax.swing.JButton();
        btnHistoria = new javax.swing.JButton();
        btnEspanol = new javax.swing.JButton();
        panelLouie = new javax.swing.JPanel();
        etiLouie = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtAreaTexto = new javax.swing.JTextArea();
        etiDialogo = new javax.swing.JLabel();
        btnCiencias = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Biblioteca");
        setModalExclusionType(java.awt.Dialog.ModalExclusionType.APPLICATION_EXCLUDE);
        setSize(new java.awt.Dimension(1009, 605));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnVolver.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnVolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/izquierda(1).png"))); // NOI18N
        btnVolver.setText("Volver al aula");
        btnVolver.setToolTipText("Regresar");
        btnVolver.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnVolver.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnVolver.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/izquierda(1).png"))); // NOI18N
        btnVolver.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/izquierda.png"))); // NOI18N
        btnVolver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnVolverMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnVolverMouseExited(evt);
            }
        });
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });
        getContentPane().add(btnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 520, 310, 100));

        etiLibroRojo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/libro-rojo.png"))); // NOI18N
        etiLibroRojo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                etiLibroRojoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                etiLibroRojoMouseExited(evt);
            }
        });
        getContentPane().add(etiLibroRojo, new org.netbeans.lib.awtextra.AbsoluteConstraints(76, 49, -1, -1));

        etiLibroAzul.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/libro-azul.png"))); // NOI18N
        etiLibroAzul.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                etiLibroAzulMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                etiLibroAzulMouseExited(evt);
            }
        });
        getContentPane().add(etiLibroAzul, new org.netbeans.lib.awtextra.AbsoluteConstraints(76, 172, -1, -1));

        etiLibroAmarillo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/libro-amarillo.png"))); // NOI18N
        etiLibroAmarillo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                etiLibroAmarilloMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                etiLibroAmarilloMouseExited(evt);
            }
        });
        getContentPane().add(etiLibroAmarillo, new org.netbeans.lib.awtextra.AbsoluteConstraints(76, 297, -1, -1));

        etiLibroVerde.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/libro-verde.png"))); // NOI18N
        etiLibroVerde.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                etiLibroVerdeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                etiLibroVerdeMouseExited(evt);
            }
        });
        getContentPane().add(etiLibroVerde, new org.netbeans.lib.awtextra.AbsoluteConstraints(76, 422, -1, -1));

        btnGeografia.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnGeografia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/tira-papel.png"))); // NOI18N
        btnGeografia.setText("Geografía");
        btnGeografia.setToolTipText("Realizar lección");
        btnGeografia.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnGeografia.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/tira-papel.png"))); // NOI18N
        btnGeografia.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/tira-papel-selected.png"))); // NOI18N
        btnGeografia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnGeografiaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnGeografiaMouseExited(evt);
            }
        });
        btnGeografia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGeografiaActionPerformed(evt);
            }
        });
        getContentPane().add(btnGeografia, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 172, 278, 72));

        btnHistoria.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnHistoria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/tira-papel.png"))); // NOI18N
        btnHistoria.setText("Historia");
        btnHistoria.setToolTipText("Realizar lección");
        btnHistoria.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnHistoria.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/tira-papel.png"))); // NOI18N
        btnHistoria.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/tira-papel-selected.png"))); // NOI18N
        btnHistoria.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnHistoriaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnHistoriaMouseExited(evt);
            }
        });
        btnHistoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHistoriaActionPerformed(evt);
            }
        });
        getContentPane().add(btnHistoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 297, 278, 72));

        btnEspanol.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnEspanol.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/tira-papel.png"))); // NOI18N
        btnEspanol.setText("Español");
        btnEspanol.setToolTipText("Realizar lección");
        btnEspanol.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEspanol.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/tira-papel.png"))); // NOI18N
        btnEspanol.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/tira-papel-selected.png"))); // NOI18N
        btnEspanol.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEspanolMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEspanolMouseExited(evt);
            }
        });
        btnEspanol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEspanolActionPerformed(evt);
            }
        });
        getContentPane().add(btnEspanol, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 49, 278, 72));

        panelLouie.setBackground(new java.awt.Color(153, 153, 255));
        panelLouie.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        etiLouie.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/louie.png"))); // NOI18N
        etiLouie.setToolTipText("Louie");
        etiLouie.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                etiLouieMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                etiLouieMouseExited(evt);
            }
        });
        panelLouie.add(etiLouie, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 390, 240, -1));

        jScrollPane2.setBorder(null);

        txtAreaTexto.setColumns(20);
        txtAreaTexto.setRows(5);
        jScrollPane2.setViewportView(txtAreaTexto);

        panelLouie.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 240, 260));

        etiDialogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/dialogo.png"))); // NOI18N
        panelLouie.add(etiDialogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 310, 422));

        getContentPane().add(panelLouie, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 0, 380, 610));

        btnCiencias.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnCiencias.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/tira-papel.png"))); // NOI18N
        btnCiencias.setText("Ciencias Naturales");
        btnCiencias.setToolTipText("Realizar lección");
        btnCiencias.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCiencias.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/tira-papel.png"))); // NOI18N
        btnCiencias.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/tira-papel-selected.png"))); // NOI18N
        btnCiencias.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCienciasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCienciasMouseExited(evt);
            }
        });
        btnCiencias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCienciasActionPerformed(evt);
            }
        });
        getContentPane().add(btnCiencias, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 422, 278, 72));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
    
     cerrar();
    }//GEN-LAST:event_formWindowClosing

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
    
    }//GEN-LAST:event_formWindowClosed

    private void etiLibroRojoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_etiLibroRojoMouseEntered
       
        etiLibroRojo.setIcon( new ImageIcon(getClass().getResource("/Recursos/libro-abierto-rojo.png")));
        aparecerDialogo();
        
        String dialogo = "Veo que te interesa el libro rojo"
                + "\nEspañol es una materia muy esencial"
                + "\nlo usarás toda tu vida."
                + "\n¿Quieres hacer una lección?\n"
                + "Solo debes presionar la palabra 'Español' "
                + "\nadelante anímate y expande tu "
                + "\nconocimiento.";
        txtAreaTexto.setText(dialogo);
    }//GEN-LAST:event_etiLibroRojoMouseEntered

    private void etiLibroRojoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_etiLibroRojoMouseExited
        etiLibroRojo.setIcon( new ImageIcon(getClass().getResource("/Recursos/libro-rojo.png")));
        desaparecerDialogo();
    }//GEN-LAST:event_etiLibroRojoMouseExited

    private void etiLibroAzulMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_etiLibroAzulMouseEntered
         
        etiLibroAzul.setIcon( new ImageIcon(getClass().getResource("/Recursos/libro-abierto-azul.png")));
        aparecerDialogo();
        
        String dialogo = "Si lo tuyo es conocer el mundo por "
                + "\nqué no intentas aprender Geografía."
                + "\nSiempre es útil conocer más allá de la "
                + "\npuerta de nuestra casa. Te lo dice un gato."
                + "\n\nPara acceder a la lección solo debes"
                + "\nhacer clic a la palabra 'Geografía'."
                + "\n¡Expande tu conocimiento y diviértete!";
        txtAreaTexto.setText(dialogo);
    }//GEN-LAST:event_etiLibroAzulMouseEntered

    private void etiLibroAzulMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_etiLibroAzulMouseExited
        etiLibroAzul.setIcon( new ImageIcon(getClass().getResource("/Recursos/libro-azul.png")));
          desaparecerDialogo();
          
    }//GEN-LAST:event_etiLibroAzulMouseExited

    private void etiLibroAmarilloMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_etiLibroAmarilloMouseEntered
        
        etiLibroAmarillo.setIcon( new ImageIcon(getClass().getResource("/Recursos/libro-abierto-amarillo.png")));
        aparecerDialogo();
        
        String dialogo = "¿Te apasiona la historia? A mí sí."
                + "\nLa historia nos ayuda a conocer lo"
                + "\nmás importante que le ha ocurrido a la"
                + "\nhumanidad cientos de años de sucesos"
                + "\nasombrosos al alcance de un clic con tu "
                + "\ngarrita.\n"
                + "\nSi quieres hacer una lección haz clic en la "
                + "\npalabra 'Historia'.\n ¡Aprender es divertido!";
        txtAreaTexto.setText(dialogo);
    }//GEN-LAST:event_etiLibroAmarilloMouseEntered

    private void etiLibroAmarilloMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_etiLibroAmarilloMouseExited
        
        etiLibroAmarillo.setIcon( new ImageIcon(getClass().getResource("/Recursos/libro-amarillo.png")));
        desaparecerDialogo();
          
    }//GEN-LAST:event_etiLibroAmarilloMouseExited

    private void etiLibroVerdeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_etiLibroVerdeMouseEntered
        
        etiLibroVerde.setIcon( new ImageIcon(getClass().getResource("/Recursos/libro-abierto-verde.png")));
        aparecerDialogo();
        
        String dialogo = "Creo que ya lo había mencionado,"
                + "\npero en serio me encanta esta materia."
                + "\nEl poder explicar con detalle cómo se"
                + "\nllevan a cabo procesos tan complejos"
                + "\ncon palabras tan simples."
                + "\n\nEl libro verde es de Ciencias Naturales,"
                + "\nel contenido te toca a ti descubrirlo."
                + "\nHaz clic en 'Ciencias Naturales' ya"
                + "\nmismo.";
        txtAreaTexto.setText(dialogo);
        
    }//GEN-LAST:event_etiLibroVerdeMouseEntered

    private void etiLibroVerdeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_etiLibroVerdeMouseExited
          
          etiLibroVerde.setIcon( new ImageIcon(getClass().getResource("/Recursos/libro-verde.png")));
          desaparecerDialogo();
          
    }//GEN-LAST:event_etiLibroVerdeMouseExited

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        cerrar();
    }//GEN-LAST:event_btnVolverActionPerformed

    private void etiLouieMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_etiLouieMouseEntered
       
       aparecerDialogo();
        
        String dialogo =  "Hola, me llamo Louie y este lugar"
                        + "\nes la biblioteca, toca, cualquiera de"
                        + "\nlos libros que aparecen en pantalla"
                        + "\ny empieza a estudiar las lecciones"
                        + "\ndisponibles."
                        + "\nPodrás pasarte todos los minijuegos"
                        + "\neducativos con ellas, además son"
                        + "\nsuperdivertidas.\n\n"
                        + "Mi materia favorita es Ciencias Naturales,"
                        + "\n¡adoro a los animales! Sobretodo a los"
                        + "\ngatos como yo.";
        txtAreaTexto.setText(dialogo);
        
    }//GEN-LAST:event_etiLouieMouseEntered

    private void etiLouieMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_etiLouieMouseExited
        desaparecerDialogo();
    }//GEN-LAST:event_etiLouieMouseExited

    private void btnEspanolMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEspanolMouseEntered
        
        etiLibroRojoMouseEntered(evt);
        
    }//GEN-LAST:event_btnEspanolMouseEntered

    private void btnEspanolMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEspanolMouseExited
        
         etiLibroRojoMouseExited(evt);
        
    }//GEN-LAST:event_btnEspanolMouseExited

    private void btnGeografiaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGeografiaMouseEntered
         
        etiLibroAzulMouseEntered(evt);
         
    }//GEN-LAST:event_btnGeografiaMouseEntered

    private void btnGeografiaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGeografiaMouseExited
       
        etiLibroAzulMouseExited(evt);
        
    }//GEN-LAST:event_btnGeografiaMouseExited

    private void btnHistoriaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHistoriaMouseEntered
        
        etiLibroAmarilloMouseEntered(evt);
        
    }//GEN-LAST:event_btnHistoriaMouseEntered

    private void btnHistoriaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHistoriaMouseExited
        
         etiLibroAmarilloMouseExited(evt);
        
    }//GEN-LAST:event_btnHistoriaMouseExited

    private void btnCienciasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCienciasMouseEntered
       
        etiLibroVerdeMouseEntered(evt);
        
    }//GEN-LAST:event_btnCienciasMouseEntered

    private void btnCienciasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCienciasMouseExited
       
        etiLibroVerdeMouseExited(evt);
        
    }//GEN-LAST:event_btnCienciasMouseExited

    private void btnVolverMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVolverMouseEntered
      
        btnVolver.setBounds(btnVolver.getX(), 420, 420, 200);
    }//GEN-LAST:event_btnVolverMouseEntered

    private void btnVolverMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVolverMouseExited
        btnVolver.setBounds(btnVolver.getX(), 520, 320, 100);
    }//GEN-LAST:event_btnVolverMouseExited

    private void btnEspanolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEspanolActionPerformed
        
        /*llamar a la ventana frmLecciones, mandarle como parámetro un identificador de la
          la materia que se eligió*/
        frmLecciones leccion = new frmLecciones(0, "Español");
        leccion.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnEspanolActionPerformed

    private void btnGeografiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGeografiaActionPerformed
        
        frmLecciones leccion = new frmLecciones(1, "Geografía");
        leccion.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_btnGeografiaActionPerformed

    private void btnHistoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHistoriaActionPerformed
        
        frmLecciones leccion = new frmLecciones(2, "Historia");
        leccion.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_btnHistoriaActionPerformed

    private void btnCienciasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCienciasActionPerformed
       
        frmLecciones leccion = new frmLecciones(3, "Ciencias Naturales");
        leccion.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCienciasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmBiblioteca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmBiblioteca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmBiblioteca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmBiblioteca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmBiblioteca().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCiencias;
    private javax.swing.JButton btnEspanol;
    private javax.swing.JButton btnGeografia;
    private javax.swing.JButton btnHistoria;
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel etiDialogo;
    private javax.swing.JLabel etiLibroAmarillo;
    private javax.swing.JLabel etiLibroAzul;
    private javax.swing.JLabel etiLibroRojo;
    private javax.swing.JLabel etiLibroVerde;
    private javax.swing.JLabel etiLouie;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel panelLouie;
    private javax.swing.JTextArea txtAreaTexto;
    // End of variables declaration//GEN-END:variables
}
