/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Proyecto;

import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JPanel;

/**
 *
 * @author matri
 */
public class frmMenuMinijuegos extends javax.swing.JFrame {

    /**
     * Creates new form frmMenuMinijuegos
     */
    Fondo fondo = new Fondo();
    
    
    public frmMenuMinijuegos() {
       
        this.setContentPane(fondo);
        initComponents();
        transparencia();
        
    }
    
    
    //fondo fel JFrame
    class Fondo extends JPanel{    
            private Image img; 
            @Override
            public void paint(Graphics g){   
                img = new ImageIcon(getClass().getResource("/Recursos/pizarra_2.jpg")).getImage();
                g.drawImage(img, 0, 0, getWidth(), getHeight(),this);
                setOpaque(false);
                super.paint(g);
            }//fin paint     
    }//fin fondo
    
    class FondoE extends JPanel{    
            private Image img; 
            @Override
            public void paint(Graphics g){   
                img = new ImageIcon(getClass().getResource("/Recursos/marco_colgante.png")).getImage();
                g.drawImage(img, 0, 0, getWidth(), getHeight(),this);
                setOpaque(false);
                super.paint(g);
            }//fin paint     
    }//fin fondo
    
    public void transparencia(){
        
        panelEspanol.setOpaque(false);
        panelGeografia.setOpaque(false);
        panelHistoria.setOpaque(false);
        panelCiencias.setOpaque(false);
        
        btnStartEs.setOpaque(false);
        btnStartEs.setBorderPainted(false);
        btnStartEs.setContentAreaFilled(false);
    }//fin transparencia
    
    
    public void cerrar(){
        try{
            this.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
            frmMenu menu = new frmMenu();
            menu.setVisible(true);
            this.dispose();
        }
        catch(Exception e){
            e.getMessage();
        }
        
    }//fin cerrar
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        panelEspanol = new javax.swing.JPanel();
        jToggleButton1 = new javax.swing.JToggleButton();
        jToggleButton2 = new javax.swing.JToggleButton();
        panelEspInfo = new FondoE();
        btnStartEs = new javax.swing.JButton();
        panelGeografia = new javax.swing.JPanel();
        panelHistoria = new javax.swing.JPanel();
        panelCiencias = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jTabbedPane1.setBackground(new java.awt.Color(51, 51, 255));
        jTabbedPane1.setToolTipText("");

        panelEspanol.setBackground(new java.awt.Color(204, 0, 204));
        panelEspanol.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jToggleButton1.setFont(new java.awt.Font("Sylfaen", 1, 24)); // NOI18N
        jToggleButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/cartas_100.png"))); // NOI18N
        jToggleButton1.setText("Memorama");
        panelEspanol.add(jToggleButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, 260, 120));

        jToggleButton2.setFont(new java.awt.Font("Sylfaen", 1, 24)); // NOI18N
        jToggleButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/question_mark_1.png"))); // NOI18N
        jToggleButton2.setText("Trivia");
        panelEspanol.add(jToggleButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, 260, 120));

        btnStartEs.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/comenzar.png"))); // NOI18N

        javax.swing.GroupLayout panelEspInfoLayout = new javax.swing.GroupLayout(panelEspInfo);
        panelEspInfo.setLayout(panelEspInfoLayout);
        panelEspInfoLayout.setHorizontalGroup(
            panelEspInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEspInfoLayout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addComponent(btnStartEs, javax.swing.GroupLayout.PREFERRED_SIZE, 263, Short.MAX_VALUE)
                .addGap(83, 83, 83))
        );
        panelEspInfoLayout.setVerticalGroup(
            panelEspInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelEspInfoLayout.createSequentialGroup()
                .addContainerGap(273, Short.MAX_VALUE)
                .addComponent(btnStartEs)
                .addGap(44, 44, 44))
        );

        panelEspanol.add(panelEspInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 10, 440, 410));

        jTabbedPane1.addTab("Español", panelEspanol);

        panelGeografia.setBackground(new java.awt.Color(0, 0, 204));

        javax.swing.GroupLayout panelGeografiaLayout = new javax.swing.GroupLayout(panelGeografia);
        panelGeografia.setLayout(panelGeografiaLayout);
        panelGeografiaLayout.setHorizontalGroup(
            panelGeografiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 768, Short.MAX_VALUE)
        );
        panelGeografiaLayout.setVerticalGroup(
            panelGeografiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 426, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Geografía", panelGeografia);

        panelHistoria.setBackground(new java.awt.Color(102, 204, 0));

        javax.swing.GroupLayout panelHistoriaLayout = new javax.swing.GroupLayout(panelHistoria);
        panelHistoria.setLayout(panelHistoriaLayout);
        panelHistoriaLayout.setHorizontalGroup(
            panelHistoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 768, Short.MAX_VALUE)
        );
        panelHistoriaLayout.setVerticalGroup(
            panelHistoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 426, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Historia", panelHistoria);

        panelCiencias.setBackground(new java.awt.Color(204, 255, 0));

        javax.swing.GroupLayout panelCienciasLayout = new javax.swing.GroupLayout(panelCiencias);
        panelCiencias.setLayout(panelCienciasLayout);
        panelCienciasLayout.setHorizontalGroup(
            panelCienciasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 768, Short.MAX_VALUE)
        );
        panelCienciasLayout.setVerticalGroup(
            panelCienciasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 426, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Ciencias Naturales", panelCiencias);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(114, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 773, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(122, 122, 122))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 454, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(101, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        cerrar();
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMenuMinijuegos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMenuMinijuegos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMenuMinijuegos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMenuMinijuegos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMenuMinijuegos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnStartEs;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JPanel panelCiencias;
    private javax.swing.JPanel panelEspInfo;
    private javax.swing.JPanel panelEspanol;
    private javax.swing.JPanel panelGeografia;
    private javax.swing.JPanel panelHistoria;
    // End of variables declaration//GEN-END:variables
}
