/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Proyecto;

import java.awt.Graphics;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;

/**
 *
 * @author marko
 */
public class frmMemorama extends javax.swing.JFrame {
    
    private boolean partidaTerminada = false;
    private int tiempoLimite = 1;
    private boolean cartaArriba = false;
    private ImageIcon imgCarta1;
    private ImageIcon imgCarta2;
    private JButton[] btnsCartaSeleccionada = new JButton[2];
    private boolean primerCartaSeleccionada = false;
    private Integer puntaje = 0;
    private Timer timer;
    public Timer t;
    public int minutos, segundos, centisegundos;
    public ActionListener acciones = new ActionListener() {

        @Override
        public void actionPerformed(ActionEvent ae) {
            ++centisegundos;
            if (centisegundos == 100) {
                centisegundos = 0;
                ++segundos;
            }
            if (segundos == 60) {
                segundos = 0;
                ++minutos;
            }
            actualizarTiempo();
            verificarTiempoLimite(minutos);
            
        }
    };
    
    
    
    /**
     * Creates new form frmMemorama
     */
    
    //instancia de fondo
     Fondo fondo = new Fondo();
     
    public frmMemorama() {
        this.setContentPane(fondo);
        initComponents();
        
        t = new Timer(10, acciones);
        transparencia();
        
        
        iniciarPartida();
    }
    
     class Fondo extends JPanel{    
            private Image img; 
            @Override
            public void paint(Graphics g){   
                img = new ImageIcon(getClass().getResource("/Recursos/pizarra_3.jpg")).getImage();
                g.drawImage(img, 0, 0, getWidth(), getHeight(),this);
                setOpaque(false);
                super.paint(g);
            }//fin paint     
    }//fin fondo
     
     class FondoPanel extends JPanel{    
            private Image img; 
            @Override
            public void paint(Graphics g){   
                img = new ImageIcon(getClass().getResource("/Recursos/marco_lineas.png")).getImage();
                g.drawImage(img, 0, 0, getWidth(), getHeight(),this);
                setOpaque(false);
                super.paint(g);
            }//fin paint     
    }//fin fondo
     
     public void transparencia(){
        panelCartas.setOpaque(false);
        panelEncabezado.setOpaque(false);
        panelLateral.setOpaque(false);
        btnInfo.setOpaque(false);
        btnInfo.setBorderPainted(false);
        btnInfo.setContentAreaFilled(false);
        
        etiMensaje.setVisible(false);
        panelInfo.setVisible(false);
        
     }//fin transparencia

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelCartas = new javax.swing.JPanel();
        btnCarta1 = new javax.swing.JButton();
        btnCarta2 = new javax.swing.JButton();
        btnCarta3 = new javax.swing.JButton();
        btnCarta4 = new javax.swing.JButton();
        btnCarta5 = new javax.swing.JButton();
        btnCarta6 = new javax.swing.JButton();
        btnCarta7 = new javax.swing.JButton();
        btnCarta8 = new javax.swing.JButton();
        btnCarta9 = new javax.swing.JButton();
        btnCarta10 = new javax.swing.JButton();
        btnCarta11 = new javax.swing.JButton();
        btnCarta12 = new javax.swing.JButton();
        panelEncabezado = new javax.swing.JPanel();
        etiEncabezado = new javax.swing.JLabel();
        btnInfo = new javax.swing.JButton();
        panelLateral = new FondoPanel();
        jLabel1 = new javax.swing.JLabel();
        etiquetaTiempo = new javax.swing.JLabel();
        lbPuntaje = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        panelInfo = new javax.swing.JPanel();
        etiMensaje = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1025, 700));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelCartas.setBackground(new java.awt.Color(255, 102, 255));

        btnCarta1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/f00.png"))); // NOI18N
        btnCarta1.setBorder(null);
        btnCarta1.setBorderPainted(false);
        btnCarta1.setContentAreaFilled(false);
        btnCarta1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnCarta1.setFocusable(false);
        btnCarta1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCarta1ActionPerformed(evt);
            }
        });

        btnCarta2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/f00.png"))); // NOI18N
        btnCarta2.setBorder(null);
        btnCarta2.setBorderPainted(false);
        btnCarta2.setContentAreaFilled(false);
        btnCarta2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnCarta2.setFocusable(false);
        btnCarta2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCarta2ActionPerformed(evt);
            }
        });

        btnCarta3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/f00.png"))); // NOI18N
        btnCarta3.setBorder(null);
        btnCarta3.setBorderPainted(false);
        btnCarta3.setContentAreaFilled(false);
        btnCarta3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnCarta3.setFocusable(false);
        btnCarta3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCarta3ActionPerformed(evt);
            }
        });

        btnCarta4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/f00.png"))); // NOI18N
        btnCarta4.setBorder(null);
        btnCarta4.setBorderPainted(false);
        btnCarta4.setContentAreaFilled(false);
        btnCarta4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnCarta4.setFocusable(false);
        btnCarta4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCarta4ActionPerformed(evt);
            }
        });

        btnCarta5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/f00.png"))); // NOI18N
        btnCarta5.setBorder(null);
        btnCarta5.setBorderPainted(false);
        btnCarta5.setContentAreaFilled(false);
        btnCarta5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnCarta5.setFocusable(false);
        btnCarta5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCarta5ActionPerformed(evt);
            }
        });

        btnCarta6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/f00.png"))); // NOI18N
        btnCarta6.setBorder(null);
        btnCarta6.setBorderPainted(false);
        btnCarta6.setContentAreaFilled(false);
        btnCarta6.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnCarta6.setFocusable(false);
        btnCarta6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCarta6ActionPerformed(evt);
            }
        });

        btnCarta7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/f00.png"))); // NOI18N
        btnCarta7.setBorder(null);
        btnCarta7.setBorderPainted(false);
        btnCarta7.setContentAreaFilled(false);
        btnCarta7.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnCarta7.setFocusable(false);
        btnCarta7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCarta7ActionPerformed(evt);
            }
        });

        btnCarta8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/f00.png"))); // NOI18N
        btnCarta8.setBorder(null);
        btnCarta8.setBorderPainted(false);
        btnCarta8.setContentAreaFilled(false);
        btnCarta8.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnCarta8.setFocusable(false);
        btnCarta8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCarta8ActionPerformed(evt);
            }
        });

        btnCarta9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/f00.png"))); // NOI18N
        btnCarta9.setBorder(null);
        btnCarta9.setBorderPainted(false);
        btnCarta9.setContentAreaFilled(false);
        btnCarta9.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnCarta9.setFocusable(false);
        btnCarta9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCarta9ActionPerformed(evt);
            }
        });

        btnCarta10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/f00.png"))); // NOI18N
        btnCarta10.setBorder(null);
        btnCarta10.setBorderPainted(false);
        btnCarta10.setContentAreaFilled(false);
        btnCarta10.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnCarta10.setFocusable(false);
        btnCarta10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCarta10ActionPerformed(evt);
            }
        });

        btnCarta11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/f00.png"))); // NOI18N
        btnCarta11.setBorder(null);
        btnCarta11.setBorderPainted(false);
        btnCarta11.setContentAreaFilled(false);
        btnCarta11.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnCarta11.setFocusable(false);
        btnCarta11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCarta11ActionPerformed(evt);
            }
        });

        btnCarta12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/f00.png"))); // NOI18N
        btnCarta12.setBorder(null);
        btnCarta12.setBorderPainted(false);
        btnCarta12.setContentAreaFilled(false);
        btnCarta12.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnCarta12.setFocusable(false);
        btnCarta12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCarta12ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelCartasLayout = new javax.swing.GroupLayout(panelCartas);
        panelCartas.setLayout(panelCartasLayout);
        panelCartasLayout.setHorizontalGroup(
            panelCartasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCartasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelCartasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCartasLayout.createSequentialGroup()
                        .addComponent(btnCarta1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(btnCarta2)
                        .addGap(18, 18, 18)
                        .addComponent(btnCarta3)
                        .addGap(18, 18, 18)
                        .addComponent(btnCarta4)
                        .addGap(348, 348, 348))
                    .addGroup(panelCartasLayout.createSequentialGroup()
                        .addGroup(panelCartasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(panelCartasLayout.createSequentialGroup()
                                .addComponent(btnCarta9)
                                .addGap(18, 18, 18)
                                .addComponent(btnCarta10)
                                .addGap(18, 18, 18)
                                .addComponent(btnCarta11))
                            .addGroup(panelCartasLayout.createSequentialGroup()
                                .addComponent(btnCarta5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnCarta6)
                                .addGap(18, 18, 18)
                                .addComponent(btnCarta7)))
                        .addGap(18, 18, 18)
                        .addGroup(panelCartasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnCarta12)
                            .addComponent(btnCarta8))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        panelCartasLayout.setVerticalGroup(
            panelCartasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCartasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelCartasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnCarta4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCarta3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCarta2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCarta1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(panelCartasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCarta8)
                    .addComponent(btnCarta7)
                    .addComponent(btnCarta6)
                    .addComponent(btnCarta5))
                .addGap(18, 18, 18)
                .addGroup(panelCartasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnCarta12)
                    .addComponent(btnCarta11)
                    .addComponent(btnCarta10)
                    .addComponent(btnCarta9))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        getContentPane().add(panelCartas, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 983, -1));

        panelEncabezado.setBackground(new java.awt.Color(255, 153, 153));

        etiEncabezado.setFont(new java.awt.Font("Sylfaen", 1, 48)); // NOI18N
        etiEncabezado.setForeground(new java.awt.Color(255, 255, 255));
        etiEncabezado.setText("Memorama");

        javax.swing.GroupLayout panelEncabezadoLayout = new javax.swing.GroupLayout(panelEncabezado);
        panelEncabezado.setLayout(panelEncabezadoLayout);
        panelEncabezadoLayout.setHorizontalGroup(
            panelEncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelEncabezadoLayout.createSequentialGroup()
                .addGap(402, 402, 402)
                .addComponent(etiEncabezado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(398, 398, 398))
        );
        panelEncabezadoLayout.setVerticalGroup(
            panelEncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelEncabezadoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(etiEncabezado)
                .addContainerGap())
        );

        getContentPane().add(panelEncabezado, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1003, 60));

        btnInfo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/info_50.png"))); // NOI18N
        btnInfo.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/info_50.png"))); // NOI18N
        btnInfo.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/info_50_light.png"))); // NOI18N
        btnInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInfoActionPerformed(evt);
            }
        });
        getContentPane().add(btnInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 70, 50, 50));

        panelLateral.setBackground(new java.awt.Color(51, 255, 51));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Puntaje:");

        etiquetaTiempo.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        etiquetaTiempo.setForeground(new java.awt.Color(255, 255, 255));
        etiquetaTiempo.setText("---");

        lbPuntaje.setBackground(new java.awt.Color(255, 255, 255));
        lbPuntaje.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbPuntaje.setForeground(new java.awt.Color(255, 255, 255));
        lbPuntaje.setText("---");

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        lbPuntaje.setText("0");

        jLabel2.setText("Tiempo:");

        javax.swing.GroupLayout panelLateralLayout = new javax.swing.GroupLayout(panelLateral);
        panelLateral.setLayout(panelLateralLayout);
        panelLateralLayout.setHorizontalGroup(
            panelLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLateralLayout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addGroup(panelLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                .addGroup(panelLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(etiquetaTiempo, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbPuntaje, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelLateralLayout.setVerticalGroup(
            panelLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLateralLayout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addGroup(panelLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbPuntaje, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(panelLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(etiquetaTiempo))
                .addGap(23, 23, 23))
        );

        getContentPane().add(panelLateral, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 70, 350, -1));

        panelInfo.setBackground(new java.awt.Color(232, 245, 159));
        panelInfo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        etiMensaje.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        etiMensaje.setForeground(new java.awt.Color(102, 102, 102));
        etiMensaje.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiMensaje.setText("¡Encuentra los pares lo más rápido que puedas!");

        javax.swing.GroupLayout panelInfoLayout = new javax.swing.GroupLayout(panelInfo);
        panelInfo.setLayout(panelInfoLayout);
        panelInfoLayout.setHorizontalGroup(
            panelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInfoLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(etiMensaje, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(40, 40, 40))
        );
        panelInfoLayout.setVerticalGroup(
            panelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInfoLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(etiMensaje)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        getContentPane().add(panelInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 510, 80));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public int[] getNumeros() {

        int[] numbers = new int[12];
        int count = 0;

        while(count < 12) {
            Random r = new Random();
            int pares = r.nextInt(6) + 1;
            int nvr = 0;

            for (int i = 0; i < 12; i++) {
                if(numbers[i] == pares) {
                    nvr++;
                }
            }
            if(nvr < 2) {
                numbers[count] = pares;
                count++;
            }//fin

        }

        return numbers;
    }
    
    public void setCards() {
        int[] numbers = getNumeros();
        
        
        btnCarta1.setDisabledIcon(new ImageIcon(getClass().getResource("/Recursos/c" + numbers[0] + ".png")));
        btnCarta2.setDisabledIcon(new ImageIcon(getClass().getResource("/Recursos/c" + numbers[1] + ".png")));
        btnCarta3.setDisabledIcon(new ImageIcon(getClass().getResource("/Recursos/c" + numbers[2] + ".png")));
        btnCarta4.setDisabledIcon(new ImageIcon(getClass().getResource("/Recursos/c" + numbers[3] + ".png")));
        btnCarta5.setDisabledIcon(new ImageIcon(getClass().getResource("/Recursos/c" + numbers[4] + ".png")));
        btnCarta6.setDisabledIcon(new ImageIcon(getClass().getResource("/Recursos/c" + numbers[5] + ".png")));
        btnCarta7.setDisabledIcon(new ImageIcon(getClass().getResource("/Recursos/c" + numbers[6] + ".png")));
        btnCarta8.setDisabledIcon(new ImageIcon(getClass().getResource("/Recursos/c" + numbers[7] + ".png")));
        btnCarta9.setDisabledIcon(new ImageIcon(getClass().getResource("/Recursos/c" + numbers[8] + ".png")));
        btnCarta10.setDisabledIcon(new ImageIcon(getClass().getResource("/Recursos/c" + numbers[9] + ".png")));
        btnCarta11.setDisabledIcon(new ImageIcon(getClass().getResource("/Recursos/c" + numbers[10] + ".png")));
        btnCarta12.setDisabledIcon(new ImageIcon(getClass().getResource("/Recursos/c" + numbers[11] + ".png")));
    }

    public void mostrarCarta(JButton btn) {

        if (cartaArriba) {
            
            imgCarta2 = (ImageIcon) btn.getDisabledIcon();
            btnsCartaSeleccionada[1] = btn;
            btnsCartaSeleccionada[1].setEnabled(false);
            primerCartaSeleccionada = true;
            puntaje += 20;
            verificarVictoria();
            
        } else {
            
            btn.setEnabled(false);
            imgCarta1 = (ImageIcon) btn.getDisabledIcon();
            btnsCartaSeleccionada[0] = btn;
            cartaArriba = true;
            primerCartaSeleccionada = false;
            
        }
    }

    public void comparar() {
        if (partidaTerminada) {
            if (cartaArriba && primerCartaSeleccionada) {

                if (imgCarta1.getDescription().compareTo(imgCarta2.getDescription()) != 0) {
                    
                    btnsCartaSeleccionada[0].setEnabled(false);
                    btnsCartaSeleccionada[1].setEnabled(false);
                    if (puntaje > 10) {
                        puntaje -= 10;
                    }
                } else {
                    
                }
                cartaArriba = false;
            }
        } else {
            if (cartaArriba && primerCartaSeleccionada) {
                
                if (imgCarta1.getDescription().compareTo(imgCarta2.getDescription()) != 0) {
                    btnsCartaSeleccionada[0].setEnabled(true);
                    timer = new Timer( 1000, new ActionListener(){
                        @Override
                        public void actionPerformed( ActionEvent e ){
                            btnsCartaSeleccionada[1].setEnabled(true);
                        }
                    } );
                    timer.setRepeats(false);
                    timer.start();  
                    if (puntaje > 10) {
                        puntaje -= 10;
                    }
                } else {
                    
                }
                cartaArriba = false;
            }
        }
        lbPuntaje.setText(puntaje.toString());
    }

    public void iniciarPartida() {
        partidaTerminada = false;
        btnCarta1.setEnabled(true);
        btnCarta1.setEnabled(true);
        btnCarta3.setEnabled(true);
        btnCarta4.setEnabled(true);
        btnCarta5.setEnabled(true);
        btnCarta6.setEnabled(true);
        btnCarta7.setEnabled(true);
        btnCarta8.setEnabled(true);
        btnCarta9.setEnabled(true);
        btnCarta10.setEnabled(true);
        btnCarta11.setEnabled(true);
        btnCarta12.setEnabled(true);

        setCards();
        
        primerCartaSeleccionada = false;
        cartaArriba = false;
        puntaje = 0;
        
        t.start();
        
    }

    public void verificarVictoria() {
        
        if (!btnCarta1.isEnabled() && !btnCarta2.isEnabled() && !btnCarta3.isEnabled() 
            && !btnCarta4.isEnabled() && !btnCarta5.isEnabled() && !btnCarta6.isEnabled()
            && !btnCarta7.isEnabled() && !btnCarta8.isEnabled() && !btnCarta9.isEnabled() 
            && !btnCarta10.isEnabled() && !btnCarta11.isEnabled() && !btnCarta12.isEnabled()) {
            t.stop();
            lbPuntaje.setText(puntaje.toString());
            JOptionPane.showMessageDialog(this, "¡Felicidades!, ¡Lo has logrado!\n            Puntaje: " + puntaje, "Pares", 0);
            
            this.dispose();
            new frmMenu().setVisible(true);
           
        }
    }
    
    void verificarTiempoLimite(int x) {
        if (x == tiempoLimite) {
            t.stop();
            
            JOptionPane.showMessageDialog(null, "¡ Tu Tiempo Termino !", "Pares",
                    0);
            centisegundos = 0;
            segundos = 0;
            minutos = 0;
            String tiempo = ("00:00:00");
            etiquetaTiempo.setText(tiempo);
            partidaTerminada = true;
            this.dispose();
            new frmMenu().setVisible(true);
        }
    }
    
    public void actualizarTiempo() {
        String tiempo = ((minutos <= 9 ? "0" : "") + minutos + ":" + (segundos <= 9 ? "0" : "") + segundos + ":" + (centisegundos <= 9 ? "0" : "") + centisegundos);
        etiquetaTiempo.setText(tiempo);
    }
    
    private void btnCarta1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCarta1ActionPerformed
        mostrarCarta(btnCarta1);
        comparar();
    }//GEN-LAST:event_btnCarta1ActionPerformed

    private void btnCarta2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCarta2ActionPerformed
        mostrarCarta(btnCarta2);
        comparar();
    }//GEN-LAST:event_btnCarta2ActionPerformed

    private void btnCarta3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCarta3ActionPerformed
        mostrarCarta(btnCarta3);
        comparar();
    }//GEN-LAST:event_btnCarta3ActionPerformed

    private void btnCarta4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCarta4ActionPerformed
        mostrarCarta(btnCarta4);
        comparar();
    }//GEN-LAST:event_btnCarta4ActionPerformed

    private void btnCarta5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCarta5ActionPerformed
        mostrarCarta(btnCarta5);
        comparar();
    }//GEN-LAST:event_btnCarta5ActionPerformed

    private void btnCarta6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCarta6ActionPerformed
        mostrarCarta(btnCarta6);
        comparar();
    }//GEN-LAST:event_btnCarta6ActionPerformed

    private void btnCarta7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCarta7ActionPerformed
        mostrarCarta(btnCarta7);
        comparar();
    }//GEN-LAST:event_btnCarta7ActionPerformed

    private void btnCarta8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCarta8ActionPerformed
        mostrarCarta(btnCarta8);
        comparar();
    }//GEN-LAST:event_btnCarta8ActionPerformed

    private void btnCarta9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCarta9ActionPerformed
        mostrarCarta(btnCarta9);
        comparar();
    }//GEN-LAST:event_btnCarta9ActionPerformed

    private void btnCarta10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCarta10ActionPerformed
        mostrarCarta(btnCarta10);
        comparar();
    }//GEN-LAST:event_btnCarta10ActionPerformed

    private void btnCarta11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCarta11ActionPerformed
        mostrarCarta(btnCarta11);
        comparar();
    }//GEN-LAST:event_btnCarta11ActionPerformed

    private void btnCarta12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCarta12ActionPerformed
        mostrarCarta(btnCarta12);
        comparar();
    }//GEN-LAST:event_btnCarta12ActionPerformed

    private void btnC1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnC1MouseExited

    }//GEN-LAST:event_btnC1MouseExited
    
    class Mensaje extends Thread{
    
        @Override
            
        public void run(){
            
            try {
                etiMensaje.setText("Toca la carta para ver su contenido");
                Thread.sleep(3000);

                etiMensaje.setText("Encuentra todos los pares y gana");
                Thread.sleep(3000);
                etiMensaje.setVisible(false);
                panelInfo.setVisible(false);
            } 
            catch (InterruptedException ex) {
                Logger.getLogger(frmMemorama.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }//fin run
        
    }//fin clase

    private void btnInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInfoActionPerformed
      
       etiMensaje.setVisible(true);
       panelInfo.setVisible(true);
       Runnable mensaje = new Mensaje();
       Thread hiloMensaje = new Thread(mensaje);
       hiloMensaje.start();
        
    }//GEN-LAST:event_btnInfoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMemorama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMemorama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMemorama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMemorama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMemorama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCarta1;
    private javax.swing.JButton btnCarta10;
    private javax.swing.JButton btnCarta11;
    private javax.swing.JButton btnCarta12;
    private javax.swing.JButton btnCarta2;
    private javax.swing.JButton btnCarta3;
    private javax.swing.JButton btnCarta4;
    private javax.swing.JButton btnCarta5;
    private javax.swing.JButton btnCarta6;
    private javax.swing.JButton btnCarta7;
    private javax.swing.JButton btnCarta8;
    private javax.swing.JButton btnCarta9;
    private javax.swing.JLabel etiquetaTiempo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lbPuntaje;
    private javax.swing.JPanel panelCartas;
    private javax.swing.JPanel panelEncabezado;
    private javax.swing.JPanel panelInfo;
    private javax.swing.JPanel panelLateral;
    private javax.swing.JButton btnInfo;
    private javax.swing.JLabel etiEncabezado;
    private javax.swing.JLabel etiMensaje;
    // End of variables declaration//GEN-END:variables
}
