/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Proyecto;

import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;

/**
 *
 * @author matri
 */
public class frmMenuMinijuegos extends javax.swing.JFrame {

    /**
     * Creates new form frmMenuMinijuegos
     */
    Fondo fondo = new Fondo();
    int id_usuario;
    
    public frmMenuMinijuegos() {
       
        this.setContentPane(fondo);
        initComponents();
        transparencia();
        componentes();
        
    }
    
    public frmMenuMinijuegos(int id) {
       id_usuario = id;
        this.setContentPane(fondo);
        initComponents();
        transparencia();
        componentes();
        
    }
    
    
    //fondo fel JFrame
    class Fondo extends JPanel{    
            private Image img; 
            @Override
            public void paint(Graphics g){   
                img = new ImageIcon(getClass().getResource("/Recursos/pizarra_2.jpg")).getImage();
                g.drawImage(img, 0, 0, getWidth(), getHeight(),this);
                setOpaque(false);
                super.paint(g);
            }//fin paint     
    }//fin fondo
    
    class FondoE extends JPanel{    
            private Image img; 
            @Override
            public void paint(Graphics g){   
                img = new ImageIcon(getClass().getResource("/Recursos/marco_colgante.png")).getImage();
                g.drawImage(img, 0, 0, getWidth(), getHeight(),this);
                setOpaque(false);
                super.paint(g);
            }//fin paint     
    }//fin fondo
    
    public void transparencia(){
        
        panelEspanol.setOpaque(false);
        panelGeografia.setOpaque(false);
        panelHistoria.setOpaque(false);
        panelCiencias.setOpaque(false);
        
        btnStartEs.setOpaque(false);
        btnStartEs.setBorderPainted(false);
        btnStartEs.setContentAreaFilled(false);
        
        btnStartGeo.setOpaque(false);
        btnStartGeo.setBorderPainted(false);
        btnStartGeo.setContentAreaFilled(false);
        
        btnStartHistoria.setOpaque(false);
        btnStartHistoria.setBorderPainted(false);
        btnStartHistoria.setContentAreaFilled(false);
        
        btnStartCiencias.setOpaque(false);
        btnStartCiencias.setBorderPainted(false);
        btnStartCiencias.setContentAreaFilled(false);
        
       
      /*  
        btnTriviaEsp.setOpaque(false);
        btnTriviaEsp.setBorderPainted(false);
        btnTriviaEsp.setContentAreaFilled(false);
        
        btnMemoramaEsp.setOpaque(false);
        btnMemoramaEsp.setBorderPainted(false);
        btnMemoramaEsp.setContentAreaFilled(false);*/
    }//fin transparencia
    
    public void componentes(){
        
        ButtonGroup grupoEsp = new ButtonGroup();       
        grupoEsp.add(btnMemoramaEsp);
        grupoEsp.add(btnTriviaEsp);
        
         ButtonGroup grupoHistoria = new ButtonGroup();       
        grupoHistoria.add(btnMemoramaHistoria);
        grupoHistoria.add(btnTriviaHistoria);
        
         ButtonGroup grupoGeo = new ButtonGroup();       
        grupoGeo.add(btnMemoramaGeo);
        grupoGeo.add(btnTriviaGeo);
        
         ButtonGroup grupoCiencias = new ButtonGroup();       
        grupoCiencias.add(btnMemoramaCiencias);
        grupoCiencias.add(btnTriviaCiencias);
        
        btnMemoramaEsp.setBackground(java.awt.Color.getHSBColor(30, 39, 100));
        btnTriviaEsp.setBackground(java.awt.Color.orange);
        
        btnMemoramaGeo.setBackground(java.awt.Color.getHSBColor(30, 39, 100));
        btnTriviaGeo.setBackground(java.awt.Color.orange);
        
        btnMemoramaHistoria.setBackground(java.awt.Color.getHSBColor(30, 39, 100));
        btnTriviaHistoria.setBackground(java.awt.Color.orange);
        
        btnMemoramaCiencias.setBackground(java.awt.Color.getHSBColor(30, 39, 100));
        btnTriviaCiencias.setBackground(java.awt.Color.orange);
    }//fin Componentes
    
    public void cerrar(){
        try{
            this.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
            frmMenu menu = new frmMenu(id_usuario);
            menu.setVisible(true);
            this.dispose();
        }
        catch(Exception e){
            e.getMessage();
        }
        
    }//fin cerrar
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        panelEspanol = new javax.swing.JPanel();
        btnMemoramaEsp = new javax.swing.JToggleButton();
        btnTriviaEsp = new javax.swing.JToggleButton();
        panelEspInfo = new FondoE();
        btnStartEs = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        etiTextoEsp = new javax.swing.JLabel();
        panelGeografia = new javax.swing.JPanel();
        panelGeoInfo = new FondoE();
        btnStartGeo = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        etiTextoGeo = new javax.swing.JLabel();
        btnMemoramaGeo = new javax.swing.JToggleButton();
        btnTriviaGeo = new javax.swing.JToggleButton();
        panelHistoria = new javax.swing.JPanel();
        panelHistoriaInfo = new FondoE();
        btnStartHistoria = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        etiTextoHistoria = new javax.swing.JLabel();
        btnTriviaHistoria = new javax.swing.JToggleButton();
        btnMemoramaHistoria = new javax.swing.JToggleButton();
        panelCiencias = new javax.swing.JPanel();
        panelCienciasInfo = new FondoE();
        btnStartCiencias = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        etiTextoCiencias = new javax.swing.JLabel();
        btnTriviaCiencias = new javax.swing.JToggleButton();
        btnMemoramaCiencias = new javax.swing.JToggleButton();
        btnInfo = new javax.swing.JButton();
        btnCerrar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jTabbedPane1.setBackground(new java.awt.Color(51, 51, 255));
        jTabbedPane1.setToolTipText("");

        panelEspanol.setBackground(new java.awt.Color(204, 0, 204));
        panelEspanol.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnMemoramaEsp.setBackground(new java.awt.Color(255, 204, 153));
        btnMemoramaEsp.setFont(new java.awt.Font("Sylfaen", 1, 24)); // NOI18N
        btnMemoramaEsp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/cartas_100.png"))); // NOI18N
        btnMemoramaEsp.setText("Memorama");
        btnMemoramaEsp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMemoramaEspActionPerformed(evt);
            }
        });
        panelEspanol.add(btnMemoramaEsp, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, 260, 120));

        btnTriviaEsp.setBackground(new java.awt.Color(255, 255, 255));
        btnTriviaEsp.setFont(new java.awt.Font("Sylfaen", 1, 24)); // NOI18N
        btnTriviaEsp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/question_mark_1.png"))); // NOI18N
        btnTriviaEsp.setSelected(true);
        btnTriviaEsp.setText("Trivia");
        btnTriviaEsp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTriviaEspActionPerformed(evt);
            }
        });
        panelEspanol.add(btnTriviaEsp, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, 260, 120));

        btnStartEs.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/comenzar.png"))); // NOI18N
        btnStartEs.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/comenzar_light.png"))); // NOI18N
        btnStartEs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartEsActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));
        jPanel1.setForeground(new java.awt.Color(0, 204, 204));
        jPanel1.setOpaque(false);

        etiTextoEsp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/triviaE.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(etiTextoEsp, javax.swing.GroupLayout.DEFAULT_SIZE, 324, Short.MAX_VALUE)
                .addGap(35, 35, 35))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(45, Short.MAX_VALUE)
                .addComponent(etiTextoEsp)
                .addContainerGap())
        );

        javax.swing.GroupLayout panelEspInfoLayout = new javax.swing.GroupLayout(panelEspInfo);
        panelEspInfo.setLayout(panelEspInfoLayout);
        panelEspInfoLayout.setHorizontalGroup(
            panelEspInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEspInfoLayout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addComponent(btnStartEs, javax.swing.GroupLayout.PREFERRED_SIZE, 263, Short.MAX_VALUE)
                .addGap(83, 83, 83))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelEspInfoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelEspInfoLayout.setVerticalGroup(
            panelEspInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelEspInfoLayout.createSequentialGroup()
                .addContainerGap(132, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnStartEs)
                .addGap(44, 44, 44))
        );

        panelEspanol.add(panelEspInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 10, 440, 410));

        jTabbedPane1.addTab("Español", panelEspanol);

        panelGeografia.setBackground(new java.awt.Color(0, 0, 204));
        panelGeografia.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnStartGeo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/comenzar.png"))); // NOI18N
        btnStartGeo.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/comenzar_light.png"))); // NOI18N
        btnStartGeo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartGeoActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(0, 204, 204));
        jPanel2.setForeground(new java.awt.Color(0, 204, 204));
        jPanel2.setOpaque(false);

        etiTextoGeo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/triviaE.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(etiTextoGeo, javax.swing.GroupLayout.DEFAULT_SIZE, 324, Short.MAX_VALUE)
                .addGap(35, 35, 35))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(45, Short.MAX_VALUE)
                .addComponent(etiTextoGeo)
                .addContainerGap())
        );

        javax.swing.GroupLayout panelGeoInfoLayout = new javax.swing.GroupLayout(panelGeoInfo);
        panelGeoInfo.setLayout(panelGeoInfoLayout);
        panelGeoInfoLayout.setHorizontalGroup(
            panelGeoInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGeoInfoLayout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addComponent(btnStartGeo, javax.swing.GroupLayout.PREFERRED_SIZE, 263, Short.MAX_VALUE)
                .addGap(83, 83, 83))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelGeoInfoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelGeoInfoLayout.setVerticalGroup(
            panelGeoInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelGeoInfoLayout.createSequentialGroup()
                .addContainerGap(132, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnStartGeo)
                .addGap(44, 44, 44))
        );

        panelGeografia.add(panelGeoInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 10, 440, 410));

        btnMemoramaGeo.setBackground(new java.awt.Color(255, 204, 153));
        btnMemoramaGeo.setFont(new java.awt.Font("Sylfaen", 1, 24)); // NOI18N
        btnMemoramaGeo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/cartas_100.png"))); // NOI18N
        btnMemoramaGeo.setText("Memorama");
        btnMemoramaGeo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMemoramaGeoActionPerformed(evt);
            }
        });
        panelGeografia.add(btnMemoramaGeo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, 260, 120));

        btnTriviaGeo.setBackground(new java.awt.Color(255, 255, 255));
        btnTriviaGeo.setFont(new java.awt.Font("Sylfaen", 1, 24)); // NOI18N
        btnTriviaGeo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/question_mark_1.png"))); // NOI18N
        btnTriviaGeo.setSelected(true);
        btnTriviaGeo.setText("Trivia");
        btnTriviaGeo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTriviaGeoActionPerformed(evt);
            }
        });
        panelGeografia.add(btnTriviaGeo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, 260, 120));

        jTabbedPane1.addTab("Geografía", panelGeografia);

        panelHistoria.setBackground(new java.awt.Color(102, 204, 0));
        panelHistoria.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnStartHistoria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/comenzar.png"))); // NOI18N
        btnStartHistoria.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/comenzar_light.png"))); // NOI18N
        btnStartHistoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartHistoriaActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(0, 204, 204));
        jPanel3.setForeground(new java.awt.Color(0, 204, 204));
        jPanel3.setOpaque(false);

        etiTextoHistoria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/triviaE.png"))); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(etiTextoHistoria, javax.swing.GroupLayout.DEFAULT_SIZE, 324, Short.MAX_VALUE)
                .addGap(35, 35, 35))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(45, Short.MAX_VALUE)
                .addComponent(etiTextoHistoria)
                .addContainerGap())
        );

        javax.swing.GroupLayout panelHistoriaInfoLayout = new javax.swing.GroupLayout(panelHistoriaInfo);
        panelHistoriaInfo.setLayout(panelHistoriaInfoLayout);
        panelHistoriaInfoLayout.setHorizontalGroup(
            panelHistoriaInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHistoriaInfoLayout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addComponent(btnStartHistoria, javax.swing.GroupLayout.PREFERRED_SIZE, 263, Short.MAX_VALUE)
                .addGap(83, 83, 83))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelHistoriaInfoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelHistoriaInfoLayout.setVerticalGroup(
            panelHistoriaInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelHistoriaInfoLayout.createSequentialGroup()
                .addContainerGap(132, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnStartHistoria)
                .addGap(44, 44, 44))
        );

        panelHistoria.add(panelHistoriaInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 10, 440, 410));

        btnTriviaHistoria.setBackground(new java.awt.Color(255, 255, 255));
        btnTriviaHistoria.setFont(new java.awt.Font("Sylfaen", 1, 24)); // NOI18N
        btnTriviaHistoria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/question_mark_1.png"))); // NOI18N
        btnTriviaHistoria.setSelected(true);
        btnTriviaHistoria.setText("Trivia");
        btnTriviaHistoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTriviaHistoriaActionPerformed(evt);
            }
        });
        panelHistoria.add(btnTriviaHistoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, 260, 120));

        btnMemoramaHistoria.setBackground(new java.awt.Color(255, 204, 153));
        btnMemoramaHistoria.setFont(new java.awt.Font("Sylfaen", 1, 24)); // NOI18N
        btnMemoramaHistoria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/cartas_100.png"))); // NOI18N
        btnMemoramaHistoria.setText("Memorama");
        btnMemoramaHistoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMemoramaHistoriaActionPerformed(evt);
            }
        });
        panelHistoria.add(btnMemoramaHistoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, 260, 120));

        jTabbedPane1.addTab("Historia", panelHistoria);

        panelCiencias.setBackground(new java.awt.Color(204, 255, 0));
        panelCiencias.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnStartCiencias.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/comenzar.png"))); // NOI18N
        btnStartCiencias.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/comenzar_light.png"))); // NOI18N
        btnStartCiencias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartCienciasActionPerformed(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(0, 204, 204));
        jPanel4.setForeground(new java.awt.Color(0, 204, 204));
        jPanel4.setOpaque(false);

        etiTextoCiencias.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/triviaE.png"))); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(etiTextoCiencias, javax.swing.GroupLayout.DEFAULT_SIZE, 324, Short.MAX_VALUE)
                .addGap(35, 35, 35))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(45, Short.MAX_VALUE)
                .addComponent(etiTextoCiencias)
                .addContainerGap())
        );

        javax.swing.GroupLayout panelCienciasInfoLayout = new javax.swing.GroupLayout(panelCienciasInfo);
        panelCienciasInfo.setLayout(panelCienciasInfoLayout);
        panelCienciasInfoLayout.setHorizontalGroup(
            panelCienciasInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCienciasInfoLayout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addComponent(btnStartCiencias, javax.swing.GroupLayout.PREFERRED_SIZE, 263, Short.MAX_VALUE)
                .addGap(83, 83, 83))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCienciasInfoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelCienciasInfoLayout.setVerticalGroup(
            panelCienciasInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCienciasInfoLayout.createSequentialGroup()
                .addContainerGap(132, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnStartCiencias)
                .addGap(44, 44, 44))
        );

        panelCiencias.add(panelCienciasInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 10, 440, 410));

        btnTriviaCiencias.setBackground(new java.awt.Color(255, 255, 255));
        btnTriviaCiencias.setFont(new java.awt.Font("Sylfaen", 1, 24)); // NOI18N
        btnTriviaCiencias.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/question_mark_1.png"))); // NOI18N
        btnTriviaCiencias.setSelected(true);
        btnTriviaCiencias.setText("Trivia");
        btnTriviaCiencias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTriviaCienciasActionPerformed(evt);
            }
        });
        panelCiencias.add(btnTriviaCiencias, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, 260, 120));

        btnMemoramaCiencias.setBackground(new java.awt.Color(255, 204, 153));
        btnMemoramaCiencias.setFont(new java.awt.Font("Sylfaen", 1, 24)); // NOI18N
        btnMemoramaCiencias.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/cartas_100.png"))); // NOI18N
        btnMemoramaCiencias.setText("Memorama");
        btnMemoramaCiencias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMemoramaCienciasActionPerformed(evt);
            }
        });
        panelCiencias.add(btnMemoramaCiencias, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, 260, 120));

        jTabbedPane1.addTab("Ciencias Naturales", panelCiencias);

        btnInfo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/info_50.png"))); // NOI18N
        btnInfo.setToolTipText("Ayuda");
        btnInfo.setBorderPainted(false);
        btnInfo.setContentAreaFilled(false);
        btnInfo.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/info_50.png"))); // NOI18N
        btnInfo.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/info_50_light.png"))); // NOI18N
        btnInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInfoActionPerformed(evt);
            }
        });

        btnCerrar.setBackground(new java.awt.Color(255, 255, 204));
        btnCerrar.setFont(new java.awt.Font("Century Schoolbook", 1, 18)); // NOI18N
        btnCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Lecciones/volver.png"))); // NOI18N
        btnCerrar.setText("Regresar");
        btnCerrar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Lecciones/volver.png"))); // NOI18N
        btnCerrar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Lecciones/volver_light.png"))); // NOI18N
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Century Schoolbook", 1, 28)); // NOI18N
        jLabel1.setText("P  I  Z  A  R  R  A");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(114, 114, 114)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 773, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(275, 275, 275)))
                .addComponent(btnInfo)
                .addGap(21, 21, 21))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 454, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnInfo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(btnCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        cerrar();
    }//GEN-LAST:event_formWindowClosing

    private void btnTriviaEspActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTriviaEspActionPerformed
        btnMemoramaEsp.setBackground(java.awt.Color.getHSBColor(30, 39, 100));
        btnTriviaEsp.setBackground(java.awt.Color.orange);
        ImageIcon img = new ImageIcon(getClass().getResource("/Recursos/triviaE.png")); 
        etiTextoEsp.setIcon(img);
        
    }//GEN-LAST:event_btnTriviaEspActionPerformed

    private void btnMemoramaEspActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMemoramaEspActionPerformed
        btnTriviaEsp.setBackground(java.awt.Color.getHSBColor(30, 39, 100));
        btnMemoramaEsp.setBackground(java.awt.Color.orange);
        ImageIcon img = new ImageIcon(getClass().getResource("/Recursos/memoramaE.png")); 
        etiTextoEsp.setIcon(img);
        //img = new ImageIcon(getClass().getResource("/Recursos/pizarra_2.jpg")).getImage();
        
    }//GEN-LAST:event_btnMemoramaEspActionPerformed

    private void btnStartEsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartEsActionPerformed
        
        if(btnTriviaEsp.isSelected()){
            frmTrivia form = new frmTrivia(1, "Español",id_usuario);
            form.setVisible(true);
            this.dispose();
        }
        
        if(btnMemoramaEsp.isSelected()){
            frmMemorama form = new frmMemorama(this.id_usuario, 1);
            form.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_btnStartEsActionPerformed

    private void btnStartGeoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartGeoActionPerformed
      if(btnTriviaGeo.isSelected()){
        frmTrivia form = new frmTrivia(2, "Geografía",id_usuario);
        form.setVisible(true);
        this.dispose();
      }
      
      if(btnMemoramaGeo.isSelected()){
            frmMemorama form = new frmMemorama(this.id_usuario, 2);
            form.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_btnStartGeoActionPerformed

    private void btnStartHistoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartHistoriaActionPerformed
        if(btnTriviaHistoria.isSelected()){
            frmTrivia form = new frmTrivia(3, "Historia",id_usuario);
            form.setVisible(true);
            this.dispose();
        }
        
        if(btnMemoramaHistoria.isSelected()){
            frmMemorama form = new frmMemorama(this.id_usuario, 3);
            form.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_btnStartHistoriaActionPerformed

    private void btnStartCienciasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartCienciasActionPerformed
        if(btnTriviaCiencias.isSelected()){
            frmTrivia form = new frmTrivia(4, "Ciencias Naturales",id_usuario);
            form.setVisible(true);
            this.dispose();
        }
        
         if(btnMemoramaCiencias.isSelected()){
            frmMemorama form = new frmMemorama(this.id_usuario, 4);
            form.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_btnStartCienciasActionPerformed

    private void btnMemoramaGeoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMemoramaGeoActionPerformed
        btnTriviaGeo.setBackground(java.awt.Color.getHSBColor(30, 39, 100));
        btnMemoramaGeo.setBackground(java.awt.Color.orange);
        ImageIcon img = new ImageIcon(getClass().getResource("/Recursos/memoramaE.png")); 
        etiTextoGeo.setIcon(img);
    }//GEN-LAST:event_btnMemoramaGeoActionPerformed

    private void btnTriviaGeoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTriviaGeoActionPerformed
          btnMemoramaGeo.setBackground(java.awt.Color.getHSBColor(30, 39, 100));
        btnTriviaGeo.setBackground(java.awt.Color.orange);
        ImageIcon img = new ImageIcon(getClass().getResource("/Recursos/triviaE.png")); 
        etiTextoGeo.setIcon(img);
    }//GEN-LAST:event_btnTriviaGeoActionPerformed

    private void btnTriviaHistoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTriviaHistoriaActionPerformed
        btnMemoramaHistoria.setBackground(java.awt.Color.getHSBColor(30, 39, 100));
        btnTriviaHistoria.setBackground(java.awt.Color.orange);
        ImageIcon img = new ImageIcon(getClass().getResource("/Recursos/triviaE.png")); 
        etiTextoHistoria.setIcon(img);
    }//GEN-LAST:event_btnTriviaHistoriaActionPerformed

    private void btnTriviaCienciasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTriviaCienciasActionPerformed
         btnMemoramaCiencias.setBackground(java.awt.Color.getHSBColor(30, 39, 100));
        btnTriviaCiencias.setBackground(java.awt.Color.orange);
        ImageIcon img = new ImageIcon(getClass().getResource("/Recursos/triviaE.png")); 
        etiTextoCiencias.setIcon(img);
    }//GEN-LAST:event_btnTriviaCienciasActionPerformed

    private void btnMemoramaHistoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMemoramaHistoriaActionPerformed
          btnTriviaHistoria.setBackground(java.awt.Color.getHSBColor(30, 39, 100));
        btnMemoramaHistoria.setBackground(java.awt.Color.orange);
        ImageIcon img = new ImageIcon(getClass().getResource("/Recursos/memoramaE.png")); 
        etiTextoHistoria.setIcon(img);
    }//GEN-LAST:event_btnMemoramaHistoriaActionPerformed

    private void btnMemoramaCienciasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMemoramaCienciasActionPerformed
          btnTriviaCiencias.setBackground(java.awt.Color.getHSBColor(30, 39, 100));
        btnMemoramaCiencias.setBackground(java.awt.Color.orange);
        ImageIcon img = new ImageIcon(getClass().getResource("/Recursos/memoramaE.png")); 
        etiTextoCiencias.setIcon(img);
    }//GEN-LAST:event_btnMemoramaCienciasActionPerformed

    private void btnInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInfoActionPerformed
       
        JOptionPane.showMessageDialog(this, "Selecciona la materia en la que quieras hacer trivia o memorama,\n dentro de ellas selecciona qué opción quieres realizar\n e inmediatamente clic en el botón 'Comenzar'", "Información", JOptionPane.INFORMATION_MESSAGE);
        
    }//GEN-LAST:event_btnInfoActionPerformed

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        cerrar();
    }//GEN-LAST:event_btnCerrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMenuMinijuegos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMenuMinijuegos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMenuMinijuegos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMenuMinijuegos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMenuMinijuegos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnInfo;
    private javax.swing.JToggleButton btnMemoramaCiencias;
    private javax.swing.JToggleButton btnMemoramaEsp;
    private javax.swing.JToggleButton btnMemoramaGeo;
    private javax.swing.JToggleButton btnMemoramaHistoria;
    private javax.swing.JButton btnStartCiencias;
    private javax.swing.JButton btnStartEs;
    private javax.swing.JButton btnStartGeo;
    private javax.swing.JButton btnStartHistoria;
    private javax.swing.JToggleButton btnTriviaCiencias;
    private javax.swing.JToggleButton btnTriviaEsp;
    private javax.swing.JToggleButton btnTriviaGeo;
    private javax.swing.JToggleButton btnTriviaHistoria;
    private javax.swing.JLabel etiTextoCiencias;
    private javax.swing.JLabel etiTextoEsp;
    private javax.swing.JLabel etiTextoGeo;
    private javax.swing.JLabel etiTextoHistoria;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel panelCiencias;
    private javax.swing.JPanel panelCienciasInfo;
    private javax.swing.JPanel panelEspInfo;
    private javax.swing.JPanel panelEspanol;
    private javax.swing.JPanel panelGeoInfo;
    private javax.swing.JPanel panelGeografia;
    private javax.swing.JPanel panelHistoria;
    private javax.swing.JPanel panelHistoriaInfo;
    // End of variables declaration//GEN-END:variables
}
